insert into amazon_book_loader.valid_unknown_subject values
('Philosophy - General'),
('Photography - General'),
('Outdoors & Nature - Outdoor Recreation'),
('History - Europe'),
('Religion & Spirituality - Christianity'),
('History - World'),
('Medicine - General'),
('Computers & Internet - General'),
('Home & Garden - Home Design'),
('Home & Garden - Gardening'),
('Sports - Water Sports'),
('Computers & Internet - Software'),
('Nonfiction - Women's Studies'),
('Cooking, Food & Wine - Cooking'),
('Cooking, Food & Wine'),
('Literature & Fiction - Poetry'),
('Musical Instruments, Mind & Body'),
('Outdoors & Nature - Travel'),
('Sports - Football'),
('Nonfiction - Politics'),
('Science - Physics'),
('Teens - Science & Technology'),
('Technology - General'),
('Medicine & Pharmacy'),
('Nonfiction - Government'),
('Home & Garden - Crafts & Hobbies'),
('Science Fiction'),
('Art - Fashion'),
('Health, Mind & Body - Psychology'),
('Literature & Fiction - Genre Fiction'),
('Literature & Fiction - Literature'),
('Reference - Almanacs & Yearbooks'),
('Computers & Internet - Computer Science'),
('Science - General'),
('Travel - Africa'),
('Health, Mind & Body - Death & Grief'),
('Teens - Horror'),
('Computers & Internet - Hardware'),
('Business & Investing - General'),
('Mystery & Thrillers - Thrillers'),
('Religion & Spirituality - General'),
('Science - Nature & Ecology'),
('Parenting & Families - Parenting'),
('Travel - Asia'),
('Law Books'),
('Erotica'),
('Children's Books - 4-8 Years'),
('Entertainment - Games'),
('Computers & Internet - Networking'),
('Comics & Graphic Novels - Comic Books'),
('Business & Investing - Investing'),
('Romance - Contemporary Romance'),
('Teens - Religion & Spirituality'),
('Travel - Australia & Oceania'),
('Computers & Internet - Computers & Society'),
('History - Africa'),
('Health, Mind & Body - Personal Health'),
('History - General'),
('Business & Investing - Management'),
('Dictionaries - General'),
('Literature & Fiction - Contemporary'),
('Science - Biological Sciences'),
('Social Sciences - General'),
('Home & Garden'),
('Teens - Mysteries'),
('Romance - Historical Romance'),
('Entertainment - Music'),
('Computers & Internet - Graphic Design'),
('Nonfiction - Transportation'),
('Sports Books'),
('Health, Mind & Body - Self-Help'),
('Nonfiction - Economics'),
('Travel Books'),
('Religion & Spirituality'),
('History - United States'),
('Sports - Golf'),
('Children's Books - Fiction'),
('Computers & Internet - Computer & Video Games'),
('Computers & Internet - Operating Systems'),
('Science - Chemistry'),
('Biographies & Memoirs - Memoirs'),
('Sports - Baseball'),
('History - Asia'),
('Literature & Fiction - General'),
('Outdoors & Nature - Field Guides'),
('Travel - General'),
('Religion & Spirituality - Hinduism'),
('Biographies & Memoirs'),
('History - Military History'),
('Children's Books - Baby-3 Years'),
('Business & Investing - Economics'),
('Teens - Health, Mind & Body'),
('Art - Photography'),
('Fantasy - General'),
('Science - Engineering'),
('Gay & Lesbian - General'),
('Children's Books - Nonfiction'),
('Sports - General'),
('Cooking, Food & Wine - General'),
('Children's Books - 9-12 Years'),
('Science - Earth Sciences'),
('Comics & Graphic Novels - Graphic Novels'),
('Reference - Encyclopedias'),
('Business & Investing - Careers'),
('Health, Mind & Body - Diets & Weight Loss'),
('Nonfiction - Education'),
('Gay & Lesbian - Fiction'),
('Nonfiction - Automotive'),
('Gay & Lesbian'),
('Computers & Internet - Biography'),
('Religion & Spirituality - Islam'),
('Investing & Finance'),
('Mystery & Thrillers'),
('Parenting & Families - Pregnancy & Childbirth'),
('Gay & Lesbian - Nonfiction'),
('Computers & Internet - Programming'),
('Science - Mathematics'),
('Reference - Foreign Languages'),
('Teens - Nonfiction'),
('Health'),
('Politics - General'),
('Crafts & Hobbies'),
('Business & Investing - Reference'),
('Reference - Atlases & Maps'),
('Entertainment - General'),
('Entertainment - Movies'),
('Art - Performing Arts'),
('Science - Technology'),
('Nonfiction - Crime'),
('Teens - Science Fiction & Fantasy'),
('Art - General'),
('Reference - Dictionaries &Thesauruses'),
('Arts & Architecture'),
('Romance - General'),
('Poetry - General'),
('Computers & Internet - Databases'),
('History - Americas'),
('Sports - Instructional'),
('Children's Books - General'),
('Literature & Fiction - Drama'),
('Outdoors & Nature - General'),
('Comics & Graphic Novels - General'),
('Art - Instructional'),
('Sports - Basketball'),
('Teens - Literature & Fiction'),
('Health, Mind & Body - Personal Relationships'),
('Home & Garden - Pet Care'),
('Teens - Social Issues'),
('Reference - General'),
('Home & Garden - Home Improvement'),
('Religion & Spirituality - Spirituality'),
('Biographies & Memoirs - Biographies'),
('History - Ancient History'),
('Parenting & Families'),
('Engineering'),
('Religion & Spirituality - Buddhism'),
('Religion & Spirituality - Judaism'),
('Health, Mind & Body - Alternative Medicine'),
('History - Australia & Oceania'),
('Health, Mind & Body - Diseases & Disorders'),
('Home & Garden - Antiques & Collectibles'),
('Art - Graphic Design'),
('Business & Investing - Personal Finance'),
('Sports - Snow Sports'),
('Nonfiction - Social Science'),
('Children's Books - Educational'),
('Literature & Fiction - Literary Criticism'),
('Health, Mind & Body - Addiction & Recovery'),
('Reference Books'),
('Home & Garden - Decorating'),
('Art - Fine Arts'),
('Health, Mind & Body - General'),
('Literature & Fiction - Short Stories'),
('Teens - Biographies & Memoirs'),
('History Books'),
('Home & Garden - General'),
('Science - Astronomy'),
('Science Fiction & Fantasy - Science Fiction'),
('Teen Books'),
('Cooking, Food & Wine - Entertaining'),
('Business & Investing - Marketing'),
('Travel - Americas'),
('Mystery & Thrillers - Mystery'),
('Health, Mind & Body - Nutrition'),
('Science & Mathematics'),
('Health, Mind & Body - Sex'),
('Home & Garden - Weddings'),
('Business & Investing - Finance'),
('Business & Investing - Accounting'),
('Outdoors & Nature - Ecology'),
('Teens - General'),
('Comics & Graphic Novels'),
('Nonfiction - Philosophy'),
('Business Books'),
('Short Stories - General'),
('Horror - General'),
('Health, Mind & Body - Exercise & Fitness'),
('Outdoors & Nature'),
('Entertainment - Humor'),
('Parenting & Families - General'),
('Health, Mind & Body - Mental Health'),
('Business & Investing - Sales'),
('Children's Books'),
('Drama (Plays)'),
('Computers & Internet'),
('Nonfiction - General'),
('Teens - Reference'),
('Travel - Europe'),
('Science Fiction & Fantasy - Fantasy'),
('Horror'),
('Sports - Soccer'),
('Literature & Fiction');

insert into amazon_book_loader.valid_format values
('poster_calendar'),
('student_calendar'),
('mini_calendar'),
('roughcut'),
('day_to_day_calendar'),
('folded_map'),
('box_calendar'),
('wall_calendar'),
('box_set'),
('bookmark_calendar'),
('unabridged'),
('abridged'),
('engagement_calendar'),
('project_calendar'),
('advent_calendar'),
('perpetual_calendar'),
('wall_map'),
('audiobook'),
('almanac_calendar'),
('desk_calendar'),
('large_print'),
('other_calendar');

insert into amazon_book_loader.valid_package_dimensions_unit_of_measure values
('FT'),
('CM'),
('MM'),
('M'),
('IN');

insert into amazon_book_loader.valid_expedited_shipping values
('Next, International'),
('Domestic, International'),
('Domestic, Second'),
('Domestic, Next'),
('Domestic'),
('Second, Next'),
('Domestic, Next, International'),
('Domestic, Second, Next'),
('Next'),
('Second, International'),
('Second'),
('International'),
('Domestic, Second, Next, International'),
('Second, Next, International'),
('Domestic, Second, International');

insert into amazon_book_loader.valid_update_delete values
('Update'),
('PartialUpdate'),
('Delete');

insert into amazon_book_loader.valid_binding values
('SheetMusic'),
('MassMarket'),
('PrintedAccessCode'),
('RingBound'),
('AudioCD'),
('FoamBook'),
('Cassette'),
('Library'),
('CdRom'),
('Map'),
('ImitationLeather'),
('Pamphlet'),
('Poster'),
('Journal'),
('PlasticComb'),
('LeatherBound'),
('SingleIssueMagazine'),
('BathBook'),
('Diary'),
('BondedLeather'),
('SpiralBound'),
('School'),
('Flexibound'),
('DvdRom'),
('LibraryMP3CD'),
('Paperback'),
('VinylBound'),
('PreloadedDigitalAudioPlayer'),
('Cards'),
('StapleBound'),
('Stationery'),
('Calendar'),
('RagBook'),
('Mp3CD'),
('LooseLeaf'),
('LibraryAudioCD'),
('CardBook'),
('HardcoverSpiral'),
('WallChart'),
('BoardBook'),
('Hardcover'),
('Textbook'),
('Comic'),
('MiscSupplies');

insert into amazon_book_loader.valid_language_value values
('Vai'),
('Palauan'),
('Niuean'),
('Fanti'),
('Navaho'),
('Masai'),
('Bambara'),
('Sindhi'),
('Middle_Dutch'),
('Santali'),
('Duala'),
('Kirundi'),
('Votic'),
('Northern_Frisian'),
('Tsonga'),
('Kanuri'),
('Umbundu'),
('Komi'),
('Eastern_Frisian'),
('Hiligaynon'),
('Kachin'),
('MiddleHighGerman'),
('Pangasinan'),
('CantoneseChinese'),
('Yiddish'),
('Ga'),
('Mossi'),
('Washo'),
('Occitan'),
('Tok_Pisin'),
('Kawi'),
('FrenchCanadian'),
('SichuanYi'),
('Konkani'),
('Nauru'),
('Traditional_Chinese'),
('Luba_Katanga'),
('Assyrian'),
('Latin'),
('SerboCroatian'),
('Zulu'),
('Georgian'),
('Aramaic'),
('Tigrinya'),
('Slovakian'),
('Tibetan'),
('SinoTibetan'),
('Ingush'),
('Nahautl'),
('Dzongkha'),
('Guarani'),
('Sidamo'),
('Batak'),
('Kurukh'),
('Herero'),
('Greek'),
('Latvian'),
('English'),
('Chinook_Jargon'),
('Croatian'),
('Chhattisgarhi'),
('Chinese'),
('Buryat'),
('Inuktitut'),
('Tatar'),
('Pali'),
('Yapese'),
('Arabic'),
('Venda'),
('Erzya'),
('Alsatian'),
('Oriya'),
('Lojban'),
('Inupiak'),
('Hindi'),
('Ewondo'),
('KarachayBalkar'),
('Afghan_Pashtu'),
('Hungarian'),
('Wolof'),
('Bosnian'),
('Vietnamese'),
('Afrihili'),
('Castillian'),
('Hokkien'),
('Romany'),
('Gbaya'),
('French_Creole'),
('Tiv'),
('Basa'),
('Simplified_Chinese'),
('Braj'),
('Mirandese'),
('Scots_Gaelic'),
('German'),
('Lezghian'),
('Basque'),
('Tumbuka'),
('Inari_Sami'),
('Mandar'),
('Chechen'),
('Nzima'),
('Dutch'),
('Sanskrit'),
('Ekajuk'),
('Grebo'),
('Bihari'),
('Welsh'),
('NorthNdebele'),
('Gondi'),
('Bashkir'),
('Kamba'),
('Gwichin'),
('Makasar'),
('ClassicalNewari'),
('Interlingua'),
('Japanese'),
('Kinyarwanda'),
('Interlingue'),
('Old_Norse'),
('Hebrew'),
('Esperanto'),
('Austronesian'),
('Sami'),
('Nyamwezi'),
('Telugu'),
('Kokborok'),
('Cherokee'),
('Armenian'),
('Bodo'),
('Sandawe'),
('Tamil'),
('Kalaallisut'),
('Gullah'),
('Low_German'),
('Dinka'),
('Garo'),
('Lamba'),
('Micmac'),
('Indic'),
('Galician'),
('Madurese'),
('Kara_Kalpak'),
('Kimbundu'),
('Farsi'),
('Khasi'),
('Mandingo'),
('Marshallese'),
('Marathi'),
('Azerbaijani'),
('Old_Persian'),
('Luo'),
('Elamite'),
('Shan'),
('Adygei'),
('Norwegian'),
('Ganda'),
('Lahnda'),
('Aragonese'),
('Yugoslavian'),
('Hittite'),
('Turkmen'),
('Zaza'),
('Tonga'),
('Sukuma'),
('Aromanian'),
('Bribri'),
('Flemish'),
('Tokelau'),
('Beja'),
('Kabyle'),
('Gothic'),
('Tamashek'),
('Pedi'),
('Swahili'),
('Luba_Lulua'),
('Pashto'),
('Norwegian_Nynorsk'),
('Yao'),
('Bliss'),
('Magahi'),
('Malagasy'),
('Tlingit'),
('Slavic'),
('Maori'),
('Catalan'),
('Igbo'),
('Ladino'),
('Luxembourgish'),
('Serer'),
('Phoenician'),
('Selkup'),
('Bini'),
('Baluchi'),
('Ottoman_Turkish'),
('Rajasthani'),
('Hausa'),
('Moldavian'),
('Classical_Syriac'),
('Kumyk'),
('Avaric'),
('Chuukese'),
('Uighur'),
('Mapudungun'),
('Setswana'),
('Maithili'),
('South_Ndebele'),
('SwissGerman'),
('Tulu'),
('Portuguese_Creole'),
('Balinese'),
('Dogri'),
('Egyptian'),
('Cayuga'),
('Tuvinian'),
('Sasak'),
('Rarotongan'),
('Maltese'),
('Assamese'),
('Kumaoni'),
('Samaritan'),
('Jula'),
('Coptic'),
('Frisian'),
('Portuguese'),
('Achinese'),
('Tereno'),
('Kalmyk'),
('Avestan'),
('Minangkabau'),
('Pampanga'),
('Old_Slavonic'),
('Cornish'),
('Bulgarian'),
('Moksha'),
('CrimeanTatar'),
('Yoruba'),
('Arawak'),
('Nyankole'),
('French'),
('Karelian'),
('Middle_Irish'),
('Bengali'),
('Angika'),
('Haitian'),
('Nepali'),
('Finnish'),
('Sundanese'),
('Albanian'),
('Hiri_Motu'),
('Tagalog'),
('Serbian'),
('Italian'),
('Luiseno'),
('Chibcha'),
('Walloon'),
('MiddleEnglish'),
('Chamorro'),
('Amharic'),
('Tajik'),
('Rapanui'),
('Urdu'),
('Lozi'),
('Tonga_Nyasa'),
('Gorontalo'),
('Chagatai'),
('Lapp'),
('Waray'),
('Nias'),
('Kutenai'),
('Fulah'),
('Buginese'),
('Cheyenne'),
('Fon'),
('Awadhi'),
('Cree'),
('Indonesian'),
('Chiricahua'),
('Hawaiian'),
('Dhivehi'),
('Chichewa'),
('Sinhalese'),
('Adangme'),
('Thai'),
('Afrikaans'),
('Ugaritic'),
('Uzbek'),
('Sranan_Tongo'),
('Zenaga'),
('Limburgan'),
('Burmese'),
('Aleut'),
('Southern_Altai'),
('Lingala'),
('Old_Provencal'),
('IndoEuropean'),
('Skolt_Sami'),
('Syriac'),
('Friulian'),
('Nyoro'),
('MiddleFrench'),
('Breton'),
('Old_Irish'),
('Turkish'),
('Delaware'),
('TaiwaneseChinese'),
('Soninke'),
('Southern_Sami'),
('Zapotec'),
('Hmong'),
('Khmer'),
('Chuvash'),
('Lithuanian'),
('Sangho'),
('Malay'),
('Tzeltal'),
('Zuni'),
('Iban'),
('Cebuano'),
('Iloko'),
('Berber'),
('Mohawk'),
('Dogrib'),
('Romansh'),
('Ukrainian'),
('Javanese'),
('LowerSorbian'),
('Kannada'),
('Persian'),
('Mongolian'),
('Choctaw'),
('Aymara'),
('Fiji'),
('Shona'),
('Chipewyan'),
('Corsican'),
('Kpelle'),
('Somali'),
('PortugueseBrazilian'),
('Arapaho'),
('Akan'),
('Lushai'),
('Tahitian'),
('Gallegan'),
('Siksika'),
('Old_High_German'),
('Dargwa'),
('Sogdian'),
('Gayo'),
('Ukranian'),
('Mongo'),
('Kuanyama'),
('Asturian'),
('Oromo'),
('Nepal_Bhasa'),
('SouthernSotho'),
('Khotanese'),
('Neapolitan'),
('Bemba'),
('Blin'),
('Quechua'),
('Estonian'),
('Fang'),
('Byelorussian'),
('Pohnpeian'),
('Sesotho'),
('Upper_Sorbian'),
('Samoan'),
('Filipino'),
('Manx'),
('Lule_Sami'),
('Galibi_Carib'),
('Kosraean'),
('Malayalam'),
('Efik'),
('Bantu'),
('Creek'),
('Bislama'),
('Kongo'),
('Acoli'),
('Timne'),
('Papiamento'),
('Marwari'),
('Dakota'),
('Polish'),
('Kirghiz'),
('Bikol'),
('Swedish'),
('Ainu'),
('Northern_Sami'),
('Mayan'),
('Mari'),
('Ewe'),
('Valencian'),
('Faroese'),
('Danish'),
('Klingon'),
('Tetum'),
('Pahlavi'),
('Slovak'),
('Gilbertese'),
('Slovene'),
('Kikuyu'),
('Punjabi'),
('Tigre'),
('Bhojpuri'),
('Tsimshian'),
('Haryanvi'),
('Nogai'),
('Bhutani'),
('Yakut'),
('Sumerian'),
('AncientGreek'),
('Xhosa'),
('Manipuri'),
('Hupa'),
('Icelandic'),
('Twi'),
('OldFrench'),
('Greenlandic'),
('Gujarati'),
('Akkadian'),
('Kashubian'),
('Korean'),
('Creole'),
('Nko'),
('Slave_Athapascan'),
('Manchu'),
('Caddo'),
('FinnoUgrian'),
('Irish'),
('MandarinChinese'),
('Kashmiri'),
('Siswati'),
('Haida'),
('Russian'),
('OldEnglish'),
('Afar'),
('Udmurt'),
('Osage'),
('Sicilian'),
('Czech'),
('Kazakh'),
('Kabardian'),
('Gahrwali'),
('Macedonian'),
('Lunda'),
('Romanian'),
('Sardinian'),
('Lao'),
('Dari'),
('Mende'),
('Mizo'),
('Ojibwa'),
('Provencal'),
('Kurdish'),
('Walamo'),
('Geez'),
('Norwegian_Bokmal'),
('Zhuang'),
('Ido'),
('Volapuk'),
('Tuvalu'),
('Abkhazian'),
('Ndonga'),
('Scots'),
('Susu'),
('Cambodian'),
('Spanish'),
('Ossetian');

insert into amazon_book_loader.valid_edition values
('6th'),
('17th'),
('3rd'),
('12th'),
('2nd'),
('5th'),
('4th'),
('14th'),
('13th'),
('19th'),
('18th'),
('20th'),
('9th'),
('1st'),
('7th'),
('11th'),
('10th'),
('16th'),
('15th'),
('8th');

insert into amazon_book_loader.valid_external_product_id_type values
('ASIN'),
('ISBN'),
('UPC'),
('EAN');

insert into amazon_book_loader.valid_condition_type values
('UsedGood'),
('CollectibleGood'),
('UsedLikeNew'),
('UsedVeryGood'),
('CollectibleAcceptable'),
('New'),
('CollectibleLikeNew'),
('CollectibleVeryGood'),
('UsedAcceptable');

insert into amazon_book_loader.valid_package_weight_unit_of_measure values
('MG'),
('LB'),
('GR'),
('OZ'),
('KG');

insert into amazon_book_loader.valid_product_tax_code values
('A_GEN_NOTAX');

insert into amazon_book_loader.valid_fulfillment_center_id values
('DEFAULT'),
('AMAZON_NA');

insert into amazon_book_loader.valid_will_ship_internationally values
('1'),
('y'),
('2'),
('n');

