insert into amazon_consumer_electronics.valid_related_product_id_type values
('GCID'),
('ASIN'),
('EAN'),
('UPC'),
('GTIN');

insert into amazon_consumer_electronics.valid_currency values
('USD');

insert into amazon_consumer_electronics.valid_cpsia_cautionary_statement values
('no_warning_applicable'),
('choking_hazard_contains_a_marble'),
('contains_small_magnets'),
('choking_hazard_is_a_marble'),
('choking_hazard_balloon'),
('choking_hazard_small_parts'),
('choking_hazard_contains_small_ball'),
('choking_hazard_is_a_small_ball');

insert into amazon_consumer_electronics.valid_website_shipping_weight_unit_of_measure values
('LB'),
('KG'),
('GR'),
('OZ');

insert into amazon_consumer_electronics.valid_country_of_origin values
('Canada'),
('Guinea-Bissau'),
('Saint Helena'),
('Unknown'),
('Lithuania'),
('Cambodia'),
('Switzerland'),
('Ethiopia'),
('Aruba'),
('Swaziland'),
('Argentina'),
('Bolivia'),
('Cameroon'),
('Burkina Faso'),
('Turkmenistan'),
('Ghana'),
('Saudi Arabia'),
('Togo'),
('Japan'),
('Cape Verde'),
('Cocos (Keeling) Islands'),
('Slovenia'),
('Guatemala'),
('Bosnia and Herzegovina'),
('Kuwait'),
('Burma (Myanmar)'),
('Jordan'),
('Dominica'),
('Liberia'),
('Maldives'),
('Jamaica'),
('Oman'),
('Tanzania'),
('Martinique'),
('Saint Kitts And Nevis'),
('Ivory Coast'),
('Albania'),
('Gabon'),
('Niue'),
('Monaco'),
('Wallis and Futuna'),
('New Zealand'),
('Yemen'),
('Jersey'),
('Andorra'),
('Greenland'),
('Samoa'),
('Macau'),
('S. Georgia and S. Sandwich Isls.'),
('Norfolk Island'),
('United Arab Emirates'),
('Guam'),
('India'),
('Azerbaijan'),
('Lesotho'),
('Saint Vincent And The Grenadines'),
('Kenya'),
('South Korea'),
('Tajikistan'),
('Turkey'),
('Afghanistan'),
('Bangladesh'),
('Mauritania'),
('Solomon Islands'),
('Saint Lucia'),
('Hungary'),
('San Marino'),
('French Polynesia'),
('France'),
('Bermuda'),
('Slovakia'),
('Somalia'),
('Peru'),
('Laos'),
('Nauru'),
('Seychelles'),
('Norway'),
('Malawi'),
('Cook Islands'),
('Benin'),
('Western Sahara'),
('Cuba'),
('Republic of the Congo'),
('Mayotte'),
('China'),
('Armenia'),
('Dominican Republic'),
('Mongolia'),
('Ukraine'),
('Bahrain'),
('Tonga'),
('Finland'),
('Libya'),
('New Caledonia'),
('Cayman Islands'),
('Central African Republic'),
('Heard and McDonald Islands'),
('Mauritius'),
('Liechtenstein'),
('Australia'),
('Antigua And Barbuda'),
('Mali'),
('Russia'),
('Bulgaria'),
('United States'),
('Romania'),
('Angola'),
('French Southern Territories'),
('Chad'),
('South Africa'),
('Tokelau'),
('Cyprus'),
('Sweden'),
('Qatar'),
('Malaysia'),
('Austria'),
('Vietnam'),
('Mozambique'),
('Uganda'),
('Canary Islands'),
('British Virgin Islands'),
('Niger'),
('Isle of Man'),
('Brazil'),
('Turks And Caicos Islands'),
('Falkland Islands'),
('Faroe Islands'),
('Guinea'),
('Panama'),
('Costa Rica'),
('Luxembourg'),
('American Samoa'),
('Bahamas'),
('Gibraltar'),
('Ireland'),
('Pakistan'),
('Palau'),
('Nigeria'),
('Ecuador'),
('Czech Republic'),
('US Virgin Islands'),
('Brunei'),
('Belarus'),
('Iran'),
('Algeria'),
('Svalbard'),
('El Salvador'),
('Tuvalu'),
('Zaire'),
('Pitcairn Islands'),
('Saint Pierre and Miquelon'),
('Marshall Islands'),
('Chile'),
('Puerto Rico'),
('Belgium'),
('Kiribati'),
('Haiti'),
('Belize'),
('Hong Kong'),
('Sierra Leone'),
('Georgia'),
('Gambia'),
('Philippines'),
('Sao Tome And Principe'),
('Moldova'),
('Holy See (Vatican City)'),
('Croatia'),
('Micronesia'),
('Guernsey'),
('Thailand'),
('Namibia'),
('Grenada'),
('Iraq'),
('Portugal'),
('Estonia'),
('Uruguay'),
('Equatorial Guinea'),
('Lebanon'),
('Uzbekistan'),
('Tunisia'),
('Djibouti'),
('Rwanda'),
('Timor-Leste'),
('Spain'),
('Colombia'),
('Reunion'),
('Burundi'),
('Taiwan'),
('Fiji'),
('Barbados'),
('Madagascar'),
('Italy'),
('Bhutan'),
('Sudan'),
('Nepal'),
('Malta'),
('Democratic Republic of the Congo'),
('Netherlands'),
('Northern Mariana Islands'),
('Suriname'),
('Anguilla'),
('Venezuela'),
('Netherlands Antilles'),
('Aland Islands'),
('Israel'),
('Indonesia'),
('Iceland'),
('Zambia'),
('Senegal'),
('Papua New Guinea'),
('Zimbabwe'),
('Germany'),
('Vanuatu'),
('Denmark'),
('Saint-Martin'),
('Kazakhstan'),
('Poland'),
('Eritrea'),
('Kyrgyzstan'),
('Palestinian Territory'),
('British Indian Ocean Territory'),
('Montserrat'),
('Mexico'),
('Macedonia'),
('North Korea'),
('Sri Lanka'),
('Latvia'),
('Guyana'),
('Syria'),
('Guadeloupe'),
('Morocco'),
('Honduras'),
('Bouvet Island'),
('Egypt'),
('Nicaragua'),
('Singapore'),
('Serbia'),
('Botswana'),
('United Kingdom'),
('Trinidad And Tobago'),
('Antarctica'),
('Christmas Island'),
('Greece'),
('Paraguay'),
('French Guiana'),
('Comoros'),
('US Minor Outlying Islands');

insert into amazon_consumer_electronics.valid_external_product_id_type values
('GCID'),
('GTIN'),
('UPC'),
('EAN');

insert into amazon_consumer_electronics.valid_battery_type values
('battery_type_d'),
('battery_type_a'),
('battery_type_c'),
('battery_type_lithium_ion'),
('battery_type_aaa'),
('battery_type_lithium_metal'),
('battery_type_9v'),
('battery_type_aa'),
('battery_type_12v'),
('battery_type_product_specific'),
('battery_type_p76'),
('battery_type_cr123a'),
('battery_type_aaaa'),
('battery_type_cr5'),
('battery_type_cr2');

insert into amazon_consumer_electronics.valid_condition_type values
('CollectibleGood'),
('CollectibleAcceptable'),
('New'),
('CollectibleLikeNew'),
('CollectibleVeryGood');

insert into amazon_consumer_electronics.valid_product_tax_code values
('A_GEN_NOTAX');

insert into amazon_consumer_electronics.valid_gtin_exemption_reason values
('ReplacementPart'),
('CustomProductBundle');

insert into amazon_consumer_electronics.valid_item_weight_unit_of_measure values
('LB'),
('KG'),
('GR'),
('OZ');

insert into amazon_consumer_electronics.valid_update_delete values
('Update'),
('PartialUpdate'),
('Delete');

insert into amazon_consumer_electronics.valid_are_batteries_included values
('True'),
('False');

insert into amazon_consumer_electronics.valid_is_discontinued_by_manufacturer values
('True'),
('False');

insert into amazon_consumer_electronics.valid_offering_can_be_giftwrapped values
('True'),
('False');

insert into amazon_consumer_electronics.valid_missing_keyset_reason values
('NonConsumer'),
('Specialized'),
('PrivateLabel'),
('PreConfigured');

insert into amazon_consumer_electronics.valid_prop_65 values
('True'),
('False');

insert into amazon_consumer_electronics.valid_package_weight_unit_of_measure values
('LB'),
('KG'),
('GR'),
('OZ');

insert into amazon_consumer_electronics.valid_offering_can_be_gift_messaged values
('True'),
('False');

insert into amazon_consumer_electronics.valid_fulfillment_center_id values
('DEFAULT'),
('AMAZON_NA');
