insert into amazon_consumer_electronics.valid_fit_type values
('Over-Ear'),
('On-Ear'),
('In-Ear');

insert into amazon_consumer_electronics.valid_item_dimensions_unit_of_measure values
('FT'),
('CM'),
('MM'),
('M'),
('IN');

insert into amazon_consumer_electronics.valid_subscription_term_name values
('7 Month Maps Subscription'),
('12 Month Maps Subscription'),
('8 Month Maps Subscription'),
('1 Month Maps Subscription'),
('15 Month Maps Subscription'),
('11 Month Maps Subscription'),
('23 Month Maps Subscription'),
('6 Month Maps Subscription'),
('2 Month Maps Subscription'),
('22 Month Maps Subscription'),
('21 Month Maps Subscription'),
('9 Month Maps Subscription'),
('Lifetime Maps'),
('4 Month Maps Subscription'),
('18 Month Maps Subscription'),
('20 Month Maps Subscription'),
('24 Month Maps Subscription'),
('16 Month Maps Subscription'),
('13 Month Maps Subscription'),
('19 Month Maps Subscription'),
('10 Month Maps Subscription'),
('5 Month Maps Subscription'),
('17 Month Maps Subscription'),
('14 Month Maps Subscription'),
('3 Month Maps Subscription');

insert into amazon_consumer_electronics.valid_tuner_technology values
('Satellite'),
('Internet Radio'),
('AM'),
('AM/FM'),
('HD Radio'),
('FM');

insert into amazon_consumer_electronics.valid_package_dimensions_unit_of_measure values
('FT'),
('CM'),
('MM'),
('M'),
('IN');

insert into amazon_consumer_electronics.valid_woofer_driver_diameter_unit_of_measure values
('FT'),
('CM'),
('MM'),
('M'),
('IN');

insert into amazon_consumer_electronics.valid_tweeter_driver_diameter_unit_of_measure values
('FT'),
('CM'),
('MM'),
('M'),
('IN');

insert into amazon_consumer_electronics.valid_map_type values
('North America'),
('Eastern Europe'),
('Africa'),
('Asia'),
('City Tour'),
('South America'),
('Saltwater'),
('Western Europe'),
('Freshwater');

insert into amazon_consumer_electronics.valid_website_shipping_weight_unit_of_measure values
('LB'),
('KG'),
('GR'),
('OZ');

insert into amazon_consumer_electronics.valid_image_brightness_unit_of_measure values
('lumens'),
('candela');

insert into amazon_consumer_electronics.valid_speaker_grille_material_type values
('Cloth'),
('Metal'),
('Plastic');

insert into amazon_consumer_electronics.valid_gps_navigation values
('Matching GPS Stamps to Geotags'),
('Location Capture'),
('GPS Enabled'),
('Geotagging');

insert into amazon_consumer_electronics.valid_mounting_hole_diameter_unit_of_measure values
('FT'),
('CM'),
('MM'),
('M'),
('IN');

insert into amazon_consumer_electronics.valid_camera_description values
('Front'),
('No Camera'),
('Video'),
('Rear');

insert into amazon_consumer_electronics.valid_battery_type values
('battery_type_d'),
('battery_type_a'),
('battery_type_c'),
('battery_type_lithium_ion'),
('battery_type_aaa'),
('battery_type_lithium_metal'),
('battery_type_9v'),
('battery_type_aa'),
('battery_type_12v'),
('battery_type_product_specific'),
('battery_type_p76'),
('battery_type_cr123a'),
('battery_type_aaaa'),
('battery_type_cr5'),
('battery_type_cr2');

insert into amazon_consumer_electronics.valid_condition_type values
('UsedGood'),
('UsedLikeNew'),
('UsedVeryGood'),
('Refurbished'),
('New'),
('UsedAcceptable');

insert into amazon_consumer_electronics.valid_traffic_features_description values
('Real-Time Traffic Compatible'),
('Includes Real-Time Traffic'),
('HD Traffic');

insert into amazon_consumer_electronics.valid_gtin_exemption_reason values
('ReplacementPart'),
('CustomProductBundle');

insert into amazon_consumer_electronics.valid_antenna_description values
('TV'),
('Satellite'),
('Radio');

insert into amazon_consumer_electronics.valid_speaker_type values
('Satellite'),
('Outdoor'),
('Surround'),
('Dual Speaker'),
('Soundbar'),
('Single Speaker'),
('Built-In'),
('Speaker Systems'),
('Center Channel'),
('Subwoofers'),
('In-Ceiling'),
('Bookshelf'),
('In-wall'),
('Floorstanding');

insert into amazon_consumer_electronics.valid_includes_remote values
('True'),
('False');

insert into amazon_consumer_electronics.valid_computer_cpu_manufacturer values
('Motorola'),
('IBM'),
('Intel'),
('AMD'),
('Qualcomm'),
('VIA'),
('Transmeta'),
('NVIDIA'),
('ARM'),
('Apple');

insert into amazon_consumer_electronics.valid_operating_system values
('CPM'),
('Sun Solaris'),
('Windows Server Enterprise Edition 2003'),
('Microsoft Windows Mobile 2003'),
('Mac OS 9.X'),
('DOS'),
('Android'),
('Mac OS X 10.4 Tiger'),
('Windows 95'),
('Windows Phone 7'),
('Windows 98'),
('Mac OS X'),
('Windows Server 2003'),
('Windows XP Home Edition'),
('Symbian'),
('Windows ME'),
('Windows 98Se'),
('Windows Server Data Center Edition 2003'),
('None'),
('Windows XP Professional Edition'),
('LindowsOS'),
('All Windows Server Versions 2000'),
('Palm OS'),
('OS2'),
('iOS'),
('Windows Server Web Edition 2003'),
('Windows XP Media Center Edition'),
('Microsoft Pocket PC 2002'),
('Windows XP Media Center 2004 Edition'),
('Mac OS X 10.3 Panther'),
('Windows NT'),
('Windows 3x and below'),
('BeOS'),
('Windows XP Professional Tablet PC Edition'),
('Chrome OS'),
('Windows 2000'),
('Tapwave Zodiac'),
('Windows Advanced Server 2003'),
('Unix'),
('Mac OS X 10.2 Jaguar'),
('Linux'),
('Windows Small Business server 2003'),
('Pre Mac OS 9'),
('Windows Mobile 6.5'),
('Sun Java Desktop System');

insert into amazon_consumer_electronics.valid_input_device_interface values
('Bluetooth included'),
('Bluetooth optional'),
('iPod cable optional'),
('HD Radio Built-in'),
('Satellite Radio optional'),
('iPod cable included'),
('iPod Built-in Dock'),
('HD Radio optional'),
('Bluetooth Built-in');

insert into amazon_consumer_electronics.valid_connectivity_technology values
('Powerline'),
('Ethernet'),
('Wireless');

insert into amazon_consumer_electronics.valid_efficiency values
('Standby Power Shutoff');

insert into amazon_consumer_electronics.valid_connector_type values
('DVI'),
('Stereo Audio'),
('HDB-15'),
('mini D15'),
('4-pin mini-DIN'),
('S-video'),
('DB-15'),
('RCA'),
('mini sub D15'),
('Composite'),
('Component'),
('D-sub 15'),
('Optical'),
('S-Video'),
('9-pin Video In/Video Out'),
('HDMI'),
('Mini sub D15'),
('USB1.0'),
('MiniHDMI'),
('USB2.0'),
('HD15 x any number'),
('USB1.1'),
('Mini D15'),
('5-way Binding Post'),
('USB3.0'),
('MiniUSB'),
('7-pin mini-DIN'),
('HD-15');

insert into amazon_consumer_electronics.valid_recommended_uses_for_product values
('Indoor/Outdoor'),
('Indoor'),
('Outdoor');

insert into amazon_consumer_electronics.valid_human_interface_input values
('keypad_pinyin'),
('Dial'),
('Keypad'),
('handwriting_recognition'),
('touch_screen'),
('touch_screen_stylus_pen'),
('Microphone'),
('trackpoint_pointing_device'),
('Buttons'),
('Keyboard'),
('keypad_stroke');

insert into amazon_consumer_electronics.valid_aspect_ratio values
('1.78:1'),
('1.33:1'),
('2.55:1'),
('2:1'),
('1.85:1'),
('1.77:1'),
('1.44:1'),
('1.75:1'),
('2.35:1'),
('1.37:1'),
('2.20:1'),
('1.66:1'),
('unknown_aspect_ratio'),
('1.55:1'),
('2.40:1');

insert into amazon_consumer_electronics.valid_supported_standards values
('WMA'),
('FLAC'),
('AAC'),
('MP3');

insert into amazon_consumer_electronics.valid_hard_disk_size_unit_of_measure values
('KB'),
('TB'),
('GB'),
('MB');

insert into amazon_consumer_electronics.valid_vehicle_speaker_size values
('15 Inch'),
('6.5 Inch'),
('3.5 Inch'),
('4.5 Inch'),
('6 by 8 Inch'),
('6 by 9 Inch'),
('4 by 6 Inch'),
('8 Inch'),
('10 Inch'),
('5 Inch'),
('5 by 7 Inch'),
('12 Inch'),
('4 Inch'),
('6.25 inch'),
('4 by 10 Inch'),
('6.75 Inch'),
('5.25 Inch');

insert into amazon_consumer_electronics.valid_shielding_type values
('Video Shielded');

insert into amazon_consumer_electronics.valid_headphones_jack values
('3.5 mm x 1'),
('3.5 mm x 2'),
('2.5 mm'),
('1/4-inch');

insert into amazon_consumer_electronics.valid_exterior_finish values
('Wood Veneer'),
('Finished Metal'),
('Painted'),
('Other'),
('Vinyl');

insert into amazon_consumer_electronics.valid_signal_conversion_supported values
('Composite to HDMI'),
('Analog Audio to HDMI'),
('Component to HDMI');

insert into amazon_consumer_electronics.valid_enclosure values
('1.5 DIN'),
('Full-DIN'),
('Double-DIN'),
('Half-DIN');

insert into amazon_consumer_electronics.valid_front_inputs_description values
('HDMI'),
('Stereo Audio'),
('Composite'),
('Component'),
('Optical'),
('S-Video'),
('USB');

insert into amazon_consumer_electronics.valid_water_resistance_level values
('not_water_resistant'),
('water_resistant'),
('waterproof');

insert into amazon_consumer_electronics.valid_video_encoding values
('DVD Video'),
('3GP'),
('AUDIO_TS'),
('QuickTime'),
('FLV'),
('MKV'),
('MP4'),
('IFO'),
('3GP2'),
('DV AVI'),
('M4V'),
('DAT'),
('ASF'),
('UHDTV'),
('DVD'),
('VRO'),
('MJPEG'),
('VIDEO_TS'),
('VCD'),
('MTS'),
('3GPP'),
('WMV'),
('HDTV'),
('Blu-ray'),
('3GPP2'),
('MPG'),
('MPEG'),
('H.263'),
('VOB'),
('M2T'),
('AVI'),
('SVCD'),
('MOD');

insert into amazon_consumer_electronics.valid_subwoofer_power_description values
('Passive'),
('Powered');

insert into amazon_consumer_electronics.valid_cooling_method values
('Water cooled'),
('Air cooled');

insert into amazon_consumer_electronics.valid_battery_cell_composition values
('Nickel-Metal Hydride'),
('Nickel-Cadmium'),
('Alkaline'),
('Lithium'),
('Lithium-Ion');

insert into amazon_consumer_electronics.valid_product_tax_code values
('A_GEN_NOTAX');

insert into amazon_consumer_electronics.valid_computer_cpu_type values
('Core 2 Quad Q8200'),
('Turion Neo X2 Dual-Core L625'),
('Atom 330'),
('Phenom II X3 Triple-Core P840'),
('Atom 230'),
('Core 2 Duo T5470'),
('Core 2 Duo T5800'),
('Core 2 Duo E4300'),
('Athlon II X2 Dual-Core P360'),
('Core i7-920'),
('Core i5-2300'),
('Athlon 2850e'),
('Core 2 Duo T5870'),
('Pentium T4500'),
('Atom D410'),
('Phenom II X4 Quad-Core 9600'),
('Sempron'),
('Phenom II X3 Triple-Core P820'),
('Pentium P6100'),
('Core i7 940'),
('Athlon Neo X2 Dual-Core L335'),
('Turion II X2 Dual-Core P520'),
('Phenom II X4 Quad Core 920'),
('Core 2 Duo T6570'),
('Athlon 64 X2 Dual Core L310'),
('Athlon II Single-Core 160u'),
('Core 2 Duo T7300'),
('Core 2 Duo T6400'),
('Texas Instruments OMAP1510'),
('Core 2 Duo T9300'),
('Core 2 Duo T2330'),
('Turion II X2 Dual Core M520'),
('Celeron 450'),
('Pentium E6700'),
('Pentium 4'),
('Core Duo T2250'),
('Core 2 Duo T7270'),
('Core 2 Duo U7700'),
('Core 2 Duo T2310'),
('Core i5-430UM'),
('Athlon 64 3500'),
('Pentium M 778'),
('Core 2 Duo E8500'),
('Core 2 Duo T5250'),
('Celeron D Processor 440'),
('Core 2 Duo P8800'),
('Athlon II X3 Triple-Core 425'),
('Celeron M 440'),
('Core i5-480M'),
('Pentium E7200'),
('Pentium E2180'),
('Core i3-520M'),
('Phenom II X2 Dual-Core N660'),
('Celeron D Processor 360'),
('Pentium U5400'),
('Core 2 Quad Q9400S'),
('Athlon 2650e'),
('Core i5-760'),
('Core 2 Duo E7600'),
('Core 2 Duo E4600'),
('Athlon 64 X2 5400+'),
('Athlon II Dual-Core 240e'),
('Pentium M 738'),
('Core 2 Quad Q6700'),
('Phenom II X4 Quad-Core 965'),
('Athlon X2 Dual-Core TK-57'),
('Core i3-330UM'),
('Athlon X2 Dual-Core TK-53'),
('Phenom II X6 Six-Core 1090T'),
('Athlon X2 Dual-Core 5400+'),
('Core 2 Duo T9600'),
('Core 2 Duo E7300'),
('Phenom II X4 Quad-Core 9150'),
('Core 2 Duo E4500'),
('Athlon 64 X2 6000+'),
('Celeron M 560'),
('Core 2 Duo P8700'),
('Pentium E8400'),
('Athlon 64 Single-Core TF-20'),
('Turion 64 X2 TL-58'),
('Pentium T4400'),
('Turion 64 X2 TL-57'),
('Turion 64 X2 TL-50'),
('Athlon 64 X2 Dual-Core 3800+'),
('Phenom II X4 Quad-Core P960'),
('Core i7-950'),
('Atom D525'),
('Core 2 Quad Q9400'),
('Core 2 Duo P9600'),
('Phenom II X3 Triple-Core 8450'),
('Pentium E2200'),
('Core i7-875K'),
('Pentium T2390'),
('Xeon'),
('Phenom II X4 Quad-Core 9100E'),
('Xeon W3503'),
('Core i3-550'),
('Core 2 Duo SL9400'),
('Phenom II X4 Quad-Core 9850'),
('Core i7-620M'),
('Turion II X2 Dual Core P560'),
('Athlon X2 Dual-Core QL-62'),
('Phenom II X4 Quad-Core 9350'),
('Turion 64 X2 ZM-72'),
('Core i7-820QM'),
('Turion 64 X2 ZM-74'),
('Phenom II X4 Quad-Core N820'),
('Athlon X2 Dual-Core 5000'),
('Core 2 Quad Q9300'),
('Core 2 Duo T9400'),
('Core 2 Duo T2450'),
('Phenom II X2 Dual-Core N620'),
('Sempron LE-1300'),
('Athlon II X4 Quad-Core 620'),
('Core 2 Quad Q9500'),
('Core Duo LV L2400'),
('Phenom II X4 Quad-Core 9450'),
('Athlon X2 Dual-Core 4200+'),
('Phenom II X4 Quad-Core P940'),
('Core i3-380UM'),
('Quad Core Q9000'),
('Pentium E7400'),
('Pentium E4400'),
('Athlon II X2 Dual-Core P320'),
('Sempron 140'),
('Xeon E5506'),
('Celeron M 530'),
('Xeon E5504'),
('Turion 64 X2 Dual-Core TL-52'),
('Turion 64 X2 Dual-Core TL-56'),
('Phenom II X4 Quad-Core 925'),
('Sempron 3600+'),
('Pentium E2140'),
('Core i7-2620QM'),
('Core i5-650'),
('Athlon 64 TF-36'),
('Core 2 Duo E6600'),
('Turion X2 Ultra Dual-Core ZM-85'),
('Sempron M100'),
('Core 2 Solo SU3500'),
('Core 2 Duo L7500'),
('Athlon II Dual-Core 245'),
('Celeron E1200'),
('Phenom II X6 Six-Core 1045T'),
('Pentium D 925'),
('Celeron M 585'),
('Phenom II X4 Quad-Core P920'),
('Core 2 Duo SP9400'),
('Core 2 Duo P3750'),
('Core 2 Duo E6400'),
('Core 2 Duo P7370'),
('Phenom II X3 Triple-Core 8550'),
('Core i5-470UM'),
('Core 2 Duo T7700'),
('Phenom II X3 Triple-Core 8650'),
('Core i5-655K'),
('Core i7-640UM'),
('Core 2 Duo U2200'),
('Core 2 Duo T9900'),
('Core 2 Duo E8400'),
('Core 2 Duo P9500'),
('Athlon Neo X2 Dual-Core L325'),
('Core i5-540M'),
('Core 2 Duo T6500'),
('Core 2 Quad Q9450'),
('Core i7-860'),
('Athlon II X2 Dual-Core 235E'),
('Celeron 743'),
('Core 2 Quad Q8200S'),
('Athlon II X2 Dual-Core 240'),
('Athlon II X2 Dual-Core 245'),
('Pentium P6000'),
('Celeron 925'),
('Core i3-350M'),
('Phenom II X3 Triple-Core B75'),
('Core 2 Duo T7200'),
('Core 2 Quad Q8300'),
('Pentium T3200'),
('Athlon II X4 Quad-Core 615e'),
('Pentium E5500'),
('Pentium T6570'),
('Phenom II X4 Quad-Core 9950'),
('Core 2 Duo T2390'),
('Athlon X2 Dual-Core QL-60'),
('Athlon X2 Dual-Core QL-66'),
('Core Duo T2400'),
('Atom N470'),
('Atom N475'),
('Core 2 Duo T7100'),
('Phenom II X4 Quad-Core N950'),
('Core 2 Quad Q8400'),
('Celeron T1500'),
('Pentium T4300'),
('Atom N270'),
('Phenom II X2 Dual-Core N650'),
('Pentium T2370'),
('Turion II Ultra X2 Dual-Core M620'),
('Celeron D Processor 420'),
('Celeron E1500'),
('Core i5-750'),
('Core 2 Duo P8400'),
('Phenom II X4 Quad-Core 955'),
('Core i7-2600'),
('Xeon E5530'),
('Core i3-530M'),
('Pentium D T2060'),
('Phenom II X4 Quad-Core 810'),
('Turion 64 X2 ZM-80'),
('Core i7-2630QM'),
('Core i7 720QM'),
('Athlon X2 Dual-Core 7550'),
('Athlon Neo Single-Core MV-40'),
('Core 2 Duo T6600'),
('Celeron M 575'),
('Core 2 Duo T5450'),
('Core 2 Quad 9600'),
('Pentium E5300'),
('Pentium E5301'),
('Core 2 Duo E7400'),
('Core 2 Duo U1400'),
('Core 2 Duo E4400'),
('Core 2 Duo T5850'),
('Core 2 Duo E6420'),
('Celeron E3300'),
('Atom Z515'),
('Atom N550'),
('Core i3-540'),
('Turion 64 X2 TL-64 Gold'),
('Core 2 Duo T5670'),
('Phenom II X3 Triple-Core N850'),
('Athlon 64 X2 4000+'),
('Pentium U5600'),
('Athlon II X4 Dual-Core 240e'),
('Turion 64 X2 Dual-Core RM-72'),
('Turion 64 X2 Dual-Core RM-70'),
('Athlon II X4 Quad-Core 605e'),
('Turion 64 X2 TL-66'),
('Core 2 Duo U7500'),
('Core i7-740QM'),
('Athlon II X2 Dual-Core 170u'),
('Xeon 3530'),
('Core 2 Duo SU9400'),
('Xeon 5400'),
('Xeon X5560'),
('Athlon II Dual-Core M320'),
('Athlon 64 4800+'),
('Core 2 Duo T7250'),
('Atom N330'),
('Core 2 Quad Q8400S'),
('Athlon II X2 Dual-Core 3250e'),
('Atom N230'),
('Pentium T2330'),
('Core i7-960'),
('Core 2 Duo T5270'),
('Athlon 64 4200+'),
('Turion 64 X2 RM-74'),
('Phenom II X4 Quad-Core 910'),
('Athlon II X2 Dual-Core M340'),
('Phenom II X4 Quad-Core N930'),
('Athlon X2 Dual-Core 7750'),
('Core i5-520M'),
('Xeon W5580'),
('Core 2 Duo T8300'),
('Core i5-660'),
('V-Series Single-Core V105'),
('Core 2 Duo SU 9600'),
('Core 2 Duo T5550'),
('Athlon II X4 Quad-Core 600E'),
('Athlon II X2 Dual-Core P340'),
('Turion X2 Dual-Core RM-75'),
('Turion II Neo X2 Dual-Core K625'),
('Athlon II Neo X2 Dual-Core K325'),
('Core 2 Duo T6670'),
('Intel Mobile CPU'),
('E-Series Dual-Core E-350'),
('Athlon II X3 Triple-Core 400E'),
('Pentium G6950'),
('Athlon II 170u'),
('V Series Single-Core V120'),
('Athlon 64 X2 QL-64 Dual Core'),
('Core 2 Duo T5300'),
('Athlon II Dual-Core P360'),
('Core i7-870'),
('Athlon II'),
('Athlon II X2 Dual-Core M520'),
('Sempron 3500+'),
('Athlon 64 X2 dual-core 4400'),
('Athlon II X2 Dual-Core 250'),
('Athlon II X2 Dual-Core 255'),
('Pentium SU2700'),
('Core 2 Duo T5600'),
('Athlon 64 X2 4200+'),
('Core 2 Duo T7350'),
('Core 2 Duo E2200'),
('Athlon 64 X2 5200+'),
('Athlon II Dual-Core 260u'),
('Celeron T3000'),
('Athlon II X2 Dual-Core 250U'),
('Athlon 64 X2 5050'),
('Turion 64 X2 Mobile'),
('C-Series C-50'),
('Atom N280'),
('Athlon II X4 Quad-Core'),
('Sempron LE-1250'),
('Sempron M120'),
('E-Series Processor E-240'),
('Core 2 Duo E6300'),
('Core 2 Duo T7500'),
('V-Series Single-Core V140'),
('Phenom II X2 Dual-Core N640'),
('Celeron E3200'),
('Turion II X2 Dual-Core M300'),
('Athlon X2 Dual-Core M300'),
('Pentium E5400'),
('Athlon II Neo X2 Dual-Core K625'),
('Core i7-680UM'),
('Core 2 Quad Q9550'),
('Xeon E5520'),
('Phenom II X4 Quad-Core 820'),
('Athlon II X2 Dual-Core M300'),
('Pentium P6200'),
('Phenom II X4 Quad-Core 945'),
('Pentium T4200'),
('Athlon 64 2650'),
('Phenom II X4 Quad-Core 9500'),
('Phenom II X6 Six-Core 1055T'),
('Turion 64 X2 TK-58'),
('Celeron M 540'),
('Core 2 Duo P7550'),
('Turion 64 X2 TK-55'),
('Turion 64 X2 TK-57'),
('Pentium E5700'),
('Turion 64 X2 TK-53'),
('Athlon 64 X2 4800'),
('Core i3-540M'),
('Athlon II Dual-Core 260'),
('Athlon 64 X2 4450B'),
('Atom Z520'),
('Atom Silverthorne'),
('Core i3-370M'),
('Core 2 Duo E4000'),
('Core i7-930'),
('Athlon II X2 Dual-Core 215'),
('Pentium E2220'),
('Pentium E6600'),
('Atom D425'),
('Phenom II X4 Quad-Core 9750'),
('Turion X2 ZM-82'),
('Turion X2 Ultra ZM-85'),
('Phenom II X4 Quad-Core 840T'),
('Core i3-530'),
('Core 2 Duo T8700'),
('Athlon II X4 Quad-Core 645'),
('Athlon 64 X2 5000+'),
('Pentium E5200'),
('Phenom II X3 Triple-Core 8400'),
('Core i3-380M'),
('Core i5-560M'),
('Athlon 64 X2 Dual Core TK-42'),
('Pentium T2080'),
('Xeon 5000'),
('Core 2 Duo T4200'),
('Pentium E6300'),
('Pentium SU4100'),
('Phenom II X3 Triple-Core N830'),
('Athlon Dual Core QL62A'),
('Celeron 900'),
('Athlon II X2 B24'),
('Athlon II X4 Quad-Core 640'),
('Core 2 Duo T9550'),
('Celeron 585'),
('Core 2 Duo E7500'),
('Athlon LE 1640'),
('Core i7-980'),
('Athlon 64 X2 6400+'),
('Core 2 Duo SL9600'),
('Phenom II X4 Quad-Core 9550'),
('Core 2 Duo P7450'),
('Atom N455'),
('Core i7-640M'),
('Atom N450'),
('Pentium E2160'),
('Pentium T2350'),
('Core 2 Duo E7200'),
('Core i7-620LM'),
('Phenom II X6 Six-Core 1035T'),
('Core Duo U2400'),
('Celeron M 353'),
('Core 2 Duo P8600'),
('Core 2 Duo E5500'),
('Pentium T2130'),
('Core Solo U1500'),
('Phenom II X2 Dual-Core 550'),
('Pentium T3400'),
('Core 2 Duo T8400'),
('Phenom II X4 Quad-Core 9650'),
('Turion II X2 Dual-Core P540'),
('Core 2 Duo P7350'),
('Atom Z330'),
('Athlon 64 X2 Dual-Core 4450'),
('Athlon II Dual-Core P320'),
('Core i7-640LM'),
('Athlon II X2 Dual-Core M320'),
('Athlon II X3 Triple-Core 435'),
('Core 2 Duo T8100'),
('Core 2 Duo SU9300'),
('Phenom II X3 Triple-Core P860'),
('Core 2 Quad Q6600'),
('Atom D510'),
('Pentium E3200'),
('Atom Z530'),
('Core 2 Duo T5750'),
('Turion 64 X2 TL-60'),
('Core 2 Duo T5200'),
('Turion 64 X2 TL-62'),
('Athlon II Neo Single-Core K125'),
('Athlon 64 X2 5600+'),
('Core i5-430M'),
('Core 2 Duo T9500'),
('Core 2 Duo SL9300'),
('Xeon 3000'),
('Core 2 Duo SU4100'),
('Geode GX'),
('Athlon II X4 Quad-Core 635'),
('Core 2 Duo SU7300'),
('Athlon II X4 Quad-Core 630'),
('Core i3-330M'),
('Athlon II X2 Dual-Core 240e'),
('Pentium T2310'),
('Turion X2 Ultra ZM-87'),
('Athlon 64'),
('Core i5-450M'),
('Turion II X2 Dual-Core M500'),
('Pentium E5800'),
('Core 2 Duo T7400'),
('Celeron M 520'),
('Core 2 Duo SL7100'),
('Athlon 64 X2 3600+'),
('Turion II Ultra X2 Dual-Core M600'),
('Phenom II X4 Quad-Core 830'),
('Celeron SU2300'),
('Core 2 Duo T5500'),
('Celeron M 550'),
('Core i5-460M'),
('Phenom II X2 Dual-Core 511'),
('Celeron M T1400');

insert into amazon_consumer_electronics.valid_has_color_screen values
('True'),
('False');

insert into amazon_consumer_electronics.valid_calibration_description values
('Manual'),
('Automatic');

insert into amazon_consumer_electronics.valid_zoom_type values
('Motorized'),
('Vari-focal'),
('Fixed'),
('Manual');

insert into amazon_consumer_electronics.valid_microphone_form_factor values
('In-line'),
('Detachable'),
('Built in');

insert into amazon_consumer_electronics.valid_speaker_connectivity values
('Wireless'),
('Wired');

insert into amazon_consumer_electronics.valid_item_weight_unit_of_measure values
('LB'),
('KG'),
('GR'),
('OZ');

insert into amazon_consumer_electronics.valid__3d_technology values
('Active'),
('Passive'),
('Anaglyphic'),
('Auto-stereoscopic (Glasses-Free)');

insert into amazon_consumer_electronics.valid_computer_cpu_speed_unit_of_measure values
('MHz'),
('GHz');

insert into amazon_consumer_electronics.valid_amplifier_connector_description values
('Tri-amp'),
('Single'),
('Bi-amp');

insert into amazon_consumer_electronics.valid_digital_audio_capacity values
('8gb'),
('80gb'),
('1.5gb'),
('40gb'),
('20gb'),
('5gb'),
('130gb'),
('512mb'),
('64mb'),
('96mb'),
('30gb'),
('300gb'),
('256mb'),
('170gb'),
('190gb'),
('200gb'),
('110gb'),
('160gb'),
('10gb'),
('32mb'),
('4gb'),
('128mb'),
('60gb'),
('400gb'),
('500gb'),
('15gb'),
('150gb'),
('140gb'),
('16mb'),
('100gb'),
('6gb'),
('120gb'),
('2gb'),
('180gb'),
('1gb');

insert into amazon_consumer_electronics.valid_supported_internet_services values
('Amazon Instant Video'),
('Explore 3D'),
('Hulu Plus'),
('Cinemanow'),
('Netflix'),
('Skype'),
('YouTube'),
('iTunes'),
('Vudu'),
('Google TV'),
('Pandora'),
('Daily Motion'),
('Free Sat/Free View'),
('Blockbuster'),
('Browser');

insert into amazon_consumer_electronics.valid_resolution_base values
('1080i'),
('720p'),
('760p'),
('720i'),
('480i'),
('1080p');

insert into amazon_consumer_electronics.valid_data_transfer_rate_unit_of_measure values
('KHz'),
('gbps'),
('mbps'),
('GHz'),
('MHz');

insert into amazon_consumer_electronics.valid_specification_met values
('Energy Star Compliant');

insert into amazon_consumer_electronics.valid_external_product_id_type values
('GCID'),
('GTIN'),
('UPC'),
('EAN');

insert into amazon_consumer_electronics.valid_included_components values
('DVD'),
('Blu-ray'),
('VHS'),
('CD'),
('Cassette'),
('dvd');

insert into amazon_consumer_electronics.valid_mounting_hole_type values
('VESA 800mm x 400mm'),
('MIS-D 100'),
('VESA 200mm x 200mm'),
('MIS-D 75'),
('VESA 100mm x 100xx'),
('MIS-F'),
('MIS-E'),
('VESA 400mm x 400mm'),
('VESA 50mm x 50mm'),
('VESA 600mm x 400mm');

insert into amazon_consumer_electronics.valid_mfg_warranty_description_type values
('Labor+Parts'),
('Parts'),
('Labor');

insert into amazon_consumer_electronics.valid_related_product_id_type values
('GCID'),
('ASIN'),
('EAN'),
('UPC'),
('GTIN');

insert into amazon_consumer_electronics.valid_projection_method values
('Front'),
('Rear-ceiling'),
('Ceiling'),
('Rear');

insert into amazon_consumer_electronics.valid_screen_surface_description values
('Matte'),
('Glossy');

insert into amazon_consumer_electronics.valid_media_type_base values
('DVD+RW'),
('VHS'),
('CD-R'),
('BD-R'),
('BD+RW'),
('DVD-R'),
('CD+RW'),
('BD+R'),
('CD+R'),
('Cassette'),
('MP3'),
('DVD+R'),
('Blu-ray');

insert into amazon_consumer_electronics.valid_audio_output_effects values
('Dolby Surround'),
('THX');

insert into amazon_consumer_electronics.valid_cpsia_cautionary_statement values
('no_warning_applicable'),
('choking_hazard_contains_a_marble'),
('contains_small_magnets'),
('choking_hazard_is_a_marble'),
('choking_hazard_balloon'),
('choking_hazard_small_parts'),
('choking_hazard_contains_small_ball'),
('choking_hazard_is_a_small_ball');

insert into amazon_consumer_electronics.valid_includes_rechargable_battery values
('True'),
('False');

insert into amazon_consumer_electronics.valid_subwoofer_diameter_unit_of_measure values
('FT'),
('CM'),
('MM'),
('M'),
('IN');

insert into amazon_consumer_electronics.valid_country_of_origin values
('Canada'),
('Guinea-Bissau'),
('Saint Helena'),
('Unknown'),
('Lithuania'),
('Cambodia'),
('Switzerland'),
('Ethiopia'),
('Aruba'),
('Swaziland'),
('Argentina'),
('Bolivia'),
('Cameroon'),
('Burkina Faso'),
('Turkmenistan'),
('Ghana'),
('Saudi Arabia'),
('Togo'),
('Japan'),
('Cape Verde'),
('Cocos (Keeling) Islands'),
('Slovenia'),
('Guatemala'),
('Bosnia and Herzegovina'),
('Kuwait'),
('Burma (Myanmar)'),
('Jordan'),
('Dominica'),
('Liberia'),
('Maldives'),
('Jamaica'),
('Oman'),
('Tanzania'),
('Martinique'),
('Saint Kitts And Nevis'),
('Ivory Coast'),
('Albania'),
('Gabon'),
('Niue'),
('Monaco'),
('Wallis and Futuna'),
('New Zealand'),
('Yemen'),
('Jersey'),
('Andorra'),
('Greenland'),
('Samoa'),
('Macau'),
('S. Georgia and S. Sandwich Isls.'),
('Norfolk Island'),
('United Arab Emirates'),
('Guam'),
('India'),
('Azerbaijan'),
('Lesotho'),
('Saint Vincent And The Grenadines'),
('Kenya'),
('South Korea'),
('Tajikistan'),
('Turkey'),
('Afghanistan'),
('Bangladesh'),
('Mauritania'),
('Solomon Islands'),
('Saint Lucia'),
('Hungary'),
('San Marino'),
('French Polynesia'),
('France'),
('Bermuda'),
('Slovakia'),
('Somalia'),
('Peru'),
('Laos'),
('Nauru'),
('Seychelles'),
('Norway'),
('Malawi'),
('Cook Islands'),
('Benin'),
('Western Sahara'),
('Cuba'),
('Republic of the Congo'),
('Mayotte'),
('China'),
('Armenia'),
('Dominican Republic'),
('Mongolia'),
('Ukraine'),
('Bahrain'),
('Tonga'),
('Finland'),
('Libya'),
('New Caledonia'),
('Cayman Islands'),
('Central African Republic'),
('Heard and McDonald Islands'),
('Mauritius'),
('Liechtenstein'),
('Australia'),
('Antigua And Barbuda'),
('Mali'),
('Russia'),
('Bulgaria'),
('United States'),
('Romania'),
('Angola'),
('French Southern Territories'),
('Chad'),
('South Africa'),
('Tokelau'),
('Cyprus'),
('Sweden'),
('Qatar'),
('Malaysia'),
('Austria'),
('Vietnam'),
('Mozambique'),
('Uganda'),
('Canary Islands'),
('British Virgin Islands'),
('Niger'),
('Isle of Man'),
('Brazil'),
('Turks And Caicos Islands'),
('Falkland Islands'),
('Faroe Islands'),
('Guinea'),
('Panama'),
('Costa Rica'),
('Luxembourg'),
('American Samoa'),
('Bahamas'),
('Gibraltar'),
('Ireland'),
('Pakistan'),
('Palau'),
('Nigeria'),
('Ecuador'),
('Czech Republic'),
('US Virgin Islands'),
('Brunei'),
('Belarus'),
('Iran'),
('Algeria'),
('Svalbard'),
('El Salvador'),
('Tuvalu'),
('Zaire'),
('Pitcairn Islands'),
('Saint Pierre and Miquelon'),
('Marshall Islands'),
('Chile'),
('Puerto Rico'),
('Belgium'),
('Kiribati'),
('Haiti'),
('Belize'),
('Hong Kong'),
('Sierra Leone'),
('Georgia'),
('Gambia'),
('Philippines'),
('Sao Tome And Principe'),
('Moldova'),
('Holy See (Vatican City)'),
('Croatia'),
('Micronesia'),
('Guernsey'),
('Thailand'),
('Namibia'),
('Grenada'),
('Iraq'),
('Portugal'),
('Estonia'),
('Uruguay'),
('Equatorial Guinea'),
('Lebanon'),
('Uzbekistan'),
('Tunisia'),
('Djibouti'),
('Rwanda'),
('Timor-Leste'),
('Spain'),
('Colombia'),
('Reunion'),
('Burundi'),
('Taiwan'),
('Fiji'),
('Barbados'),
('Madagascar'),
('Italy'),
('Bhutan'),
('Sudan'),
('Nepal'),
('Malta'),
('Democratic Republic of the Congo'),
('Netherlands'),
('Northern Mariana Islands'),
('Suriname'),
('Anguilla'),
('Venezuela'),
('Netherlands Antilles'),
('Aland Islands'),
('Israel'),
('Indonesia'),
('Iceland'),
('Zambia'),
('Senegal'),
('Papua New Guinea'),
('Zimbabwe'),
('Germany'),
('Vanuatu'),
('Denmark'),
('Saint-Martin'),
('Kazakhstan'),
('Poland'),
('Eritrea'),
('Kyrgyzstan'),
('Palestinian Territory'),
('British Indian Ocean Territory'),
('Montserrat'),
('Mexico'),
('Macedonia'),
('North Korea'),
('Sri Lanka'),
('Latvia'),
('Guyana'),
('Syria'),
('Guadeloupe'),
('Morocco'),
('Honduras'),
('Bouvet Island'),
('Egypt'),
('Nicaragua'),
('Singapore'),
('Serbia'),
('Botswana'),
('United Kingdom'),
('Trinidad And Tobago'),
('Antarctica'),
('Christmas Island'),
('Greece'),
('Paraguay'),
('French Guiana'),
('Comoros'),
('US Minor Outlying Islands');

insert into amazon_consumer_electronics.valid_s_video_connector_type values
('9-pin Video In/Video Out'),
('4-pin mini-DIN'),
('7-pin mini-DIN');

insert into amazon_consumer_electronics.valid_control_type values
('In-line Volume');

