insert into amazon_home_improvement.valid_item_dimensions_unit_of_measure values
('FT'),
('CM'),
('MM'),
('M'),
('Gauge'),
('IN');

insert into amazon_home_improvement.valid_noise_level_unit_of_measure values
('dB'),
('Sone');

insert into amazon_home_improvement.valid_maximum_diameter_unit_of_measure values
('FT'),
('CM'),
('MM'),
('M'),
('Gauge'),
('IN');

insert into amazon_home_improvement.valid_toilet_rough_in_measurement_unit_of_measure values
('FT'),
('CM'),
('MM'),
('M'),
('Gauge'),
('IN');

insert into amazon_home_improvement.valid_item_display_weight_unit_of_measure values
('LB'),
('KG'),
('GR'),
('OZ');

insert into amazon_home_improvement.valid_handle_material values
('Acrylic'),
('Ceramic'),
('Metal'),
('Porcelain');

insert into amazon_home_improvement.valid_website_shipping_weight_unit_of_measure values
('LB'),
('KG'),
('GR'),
('OZ');

insert into amazon_home_improvement.valid_water_consumption_unit_of_measure values
('GallonsPerMinute'),
('GallonsPerFlush'),
('GallonsPerHour');

insert into amazon_home_improvement.valid_condition_type values
('UsedGood'),
('CollectibleGood'),
('Club'),
('UsedLikeNew'),
('UsedVeryGood'),
('CollectibleAcceptable'),
('Refurbished'),
('New'),
('CollectibleLikeNew'),
('CollectibleVeryGood'),
('UsedAcceptable');

insert into amazon_home_improvement.valid_parent_child values
('parent'),
('child');

insert into amazon_home_improvement.valid_gtin_exemption_reason values
('ReplacementPart'),
('CustomProductBundle');

insert into amazon_home_improvement.valid_spout_reach_unit_of_measure values
('FT'),
('CM'),
('MM'),
('M'),
('Gauge'),
('IN');

insert into amazon_home_improvement.valid_blade_length_unit_of_measure values
('FT'),
('CM'),
('MM'),
('M'),
('Gauge'),
('IN');

insert into amazon_home_improvement.valid_item_display_length_unit_of_measure values
('FT'),
('CM'),
('MM'),
('M'),
('Gauge'),
('IN');

insert into amazon_home_improvement.valid_size_name values
('Medium'),
('Pocket Size'),
('Key Chain Size'),
('Large'),
('Small'),
('Full Size');

insert into amazon_home_improvement.valid_item_display_width_unit_of_measure values
('FT'),
('CM'),
('MM'),
('M'),
('Gauge'),
('IN');

insert into amazon_home_improvement.valid_color_map values
('Blue'),
('Brown'),
('Gold'),
('Copper'),
('Purple'),
('Grey'),
('Yellow'),
('Multicolored'),
('Black'),
('Red'),
('Pink'),
('Orange'),
('Green'),
('White'),
('Silver'),
('Bronze'),
('Cream');

insert into amazon_home_improvement.valid_inside_diameter_unit_of_measure values
('FT'),
('CM'),
('MM'),
('M'),
('Gauge'),
('IN');

insert into amazon_home_improvement.valid_screw_head_style values
('Philips'),
('Flat'),
('Slotted'),
('Square Torx'),
('Hex');

insert into amazon_home_improvement.valid_center_length_unit_of_measure values
('FT'),
('CM'),
('MM'),
('M'),
('Gauge'),
('IN');

insert into amazon_home_improvement.valid_variation_theme values
('Style'),
('SizeName'),
('Color'),
('Pattern'),
('SizeName-ColorName');

insert into amazon_home_improvement.valid_size_map values
('Medium'),
('XXXXX-Large'),
('XXXX-Small'),
('X-Large'),
('XX-Large'),
('Large'),
('XXXXX-Small'),
('XXX-Small'),
('XXX-Large'),
('Small'),
('XX-Small'),
('XXXX-Large'),
('X-Small');

insert into amazon_home_improvement.valid_plug_type values
('M - Two large round plugs with ground plug.'),
('G - Square plugs. British type.'),
('L - Round plugs with aligned ground plug.'),
('E - Two round plugs with male ground plug.'),
('I - Inversed V plugs with ground plug.'),
('B - US style with ground plug.'),
('F - "Schuko" type with two ground plugs.'),
('K - Plug-in plugs: rectangular with ground plug.'),
('J - Round plug with ground plug.'),
('C - Two round plugs. French type.'),
('A- US style'),
('D - Two round plugs with ground plug. French type with ground plug.'),
('H - V plugs with ground plug.');

insert into amazon_home_improvement.valid_hose_length_unit_of_measure values
('FT'),
('CM'),
('MM'),
('M'),
('Gauge'),
('IN');

insert into amazon_home_improvement.valid_cutting_diameter_unit_of_measure values
('FT'),
('CM'),
('MM'),
('M'),
('Gauge'),
('IN');

insert into amazon_home_improvement.valid_fastening_type values
('Keyed Chuck'),
('PSA'),
('1/2-Inch Square'),
('#30 Biscuit'),
('1/4-inch'),
('#20 Biscuit'),
('SDS Plus'),
('Quick Connect'),
('3/8-inch'),
('Keyless Chuck'),
('5/8 Inch - 11 Arbor'),
('3/8-inch chuck'),
('T-Shank'),
('Hook and Loop'),
('1/4-Inch Arbor'),
('1/4-inch arbor'),
('1/4 Inch'),
('3/8-Inch'),
('SDS Plus Hex'),
('No. 20 Biscut'),
('3/8-inch arbor'),
('SDS Max'),
('No. 30 Biscut'),
('Hex'),
('3/8-Inch Arbor'),
('1/2-inch chuck'),
('1/2-inch square'),
('7/16-inch arbor'),
('1/2-inch'),
('3/8-Inch Chuck'),
('5/8-inch - 11 Arbor'),
('SDS'),
('Rapid Load'),
('Universal'),
('No. 10 Biscut'),
('#10 Biscuit'),
('1/2-inch Arbor'),
('1/2-Inch'),
('Spline'),
('1/2-Inch Chuck');

insert into amazon_home_improvement.valid_energy_guide_cost_disclosure values
('2007_dishwasher'),
('2007_clothes_washer'),
('2012_oil'),
('2007_propane'),
('2007_natural_gas'),
('2012_natural_gas'),
('2012_propane'),
('2012_clothes_washer'),
('2012_electricity'),
('2012_dishwasher'),
('2007_oil'),
('2007_electricity');

insert into amazon_home_improvement.valid_relationship_type values
('Variation'),
('Accessory');

insert into amazon_home_improvement.valid_item_display_diameter_unit_of_measure values
('FT'),
('CM'),
('MM'),
('M'),
('Gauge'),
('IN');

insert into amazon_home_improvement.valid_specific_uses_for_product values
('Cured Concrete'),
('Metal cutting'),
('Concrete Drilling'),
('Concrete Grinding'),
('Stud Cutting'),
('Wet Concrete'),
('Commercial'),
('Hard Brick'),
('Commercial/Residential'),
('Concrete Cutting'),
('Residential'),
('Granite'),
('Wood Cutting'),
('Metal Cutting'),
('Fine Finish'),
('Masonry Grinding'),
('Porcelain'),
('Bar Cutting'),
('Finish Cutting'),
('Concrete/Masonry'),
('Concrete Polishing'),
('Masonry Cutting'),
('Hard Material'),
('Steel Drilling'),
('Metal Grinding'),
('Iron Cutting'),
('Metal Drilling'),
('Wood Drilling'),
('Rough Cutting'),
('Laminate Cutting'),
('General Purpose'),
('Asphalt'),
('Tuck Point'),
('Green Concrete'),
('Fast Wood Cutting'),
('Masonry Drilling');

insert into amazon_home_improvement.valid_package_length_unit_of_measure values
('FT'),
('CM'),
('MM'),
('M'),
('Gauge'),
('IN');

insert into amazon_home_improvement.valid_style_name values
('Animals'),
('Nature'),
('Food'),
('Sports'),
('Shapes/Stripes'),
('Cartoons'),
('Floral'),
('Transportation'),
('TV/Movie'),
('Princess'),
('Disney');

insert into amazon_home_improvement.valid_battery_cell_composition values
('lithium_polymer'),
('Nickel-Metal Hydride'),
('silver_oxide'),
('lithium_manganese_dioxide'),
('Nickel-Cadmium'),
('Alkaline'),
('sealed_lead_acid'),
('manganese'),
('polymer'),
('zinc'),
('lead_acid'),
('aluminum_oxygen'),
('Lithium'),
('lead_calcium'),
('Lithium-Ion');

insert into amazon_home_improvement.valid_product_tax_code values
('A_GEN_NOTAX');

insert into amazon_home_improvement.valid_item_weight_unit_of_measure values
('LB'),
('KG'),
('GR'),
('OZ');

insert into amazon_home_improvement.valid_battery_average_life_unit_of_measure values
('hours'),
('minutes'),
('days');

insert into amazon_home_improvement.valid_specification_met values
('ANSI Grade 1'),
('ANSI Grade 2'),
('ANSI Grade 3'),
('Low-lead Compliant'),
('ADA Compliant'),
('ANSI Type II - AP'),
('ANSI Standards'),
('GFCI'),
('ANSI Type IAA'),
('OSHA Compliant'),
('NFPA 1999'),
('WaterSense'),
('ANSI-Rated'),
('ANSI Type I'),
('NIOSH Certification'),
('ANSI Z87.1-2003, CSA Z94.3-2007'),
('ANSI Type III'),
('ETL Listed'),
('ENERGY STAR'),
('ANSI/ISEA 107-2004 Compliant'),
('CA Prop 65 Compliant'),
('ANSI Type II'),
('ANSI Type IA'),
('UL'),
('NSF Certification');

insert into amazon_home_improvement.valid_external_product_id_type values
('GCID'),
('GTIN'),
('UPC'),
('EAN');

insert into amazon_home_improvement.valid_included_components values
('Type 1 Guard'),
('TEKS noicepeice'),
('Drywall Nosepeice'),
('Blade Guard'),
('Toilet Tank'),
('Valve'),
('Handles'),
('Circular Saw Blade'),
('Includes Sidespray'),
('Blade Wrench'),
('Detector'),
('Jig Saw Blade'),
('Comes as a Combo Set'),
('Drill Bits'),
('Hose'),
('Depth Rod'),
('1/8-Inch Collet'),
('Shade protector'),
('Pads'),
('Side Handle'),
('Pocket Clips'),
('30-Minute Charger'),
('Reciprocating Saw Blade'),
('Fuse'),
('1/2-Inch Collet'),
('Quick Connect Fixtures'),
('Case'),
('Compartments Included'),
('Charger'),
('Blade'),
('Built-In Water Filter'),
('Bag'),
('Switch'),
('Type 27 Guard'),
('Caribineer'),
('Wrench'),
('Light'),
('Safety Gloves'),
('Screwdriver Bits'),
('Surge protection'),
('Safety Glasses'),
('1/4-Inch Collet'),
('Ear protection'),
('Drywall Bit'),
('Batteries'),
('One Hour Charger'),
('Toilet Bowl'),
('Hammer');

insert into amazon_home_improvement.valid_handle_location values
('Right'),
('Center'),
('Push Button'),
('Horizontal'),
('Automatic'),
('Veritical'),
('Left');

insert into amazon_home_improvement.valid_tubing_outside_diameter_unit_of_measure values
('FT'),
('CM'),
('MM'),
('M'),
('Gauge'),
('IN');

insert into amazon_home_improvement.valid_related_product_id_type values
('GCID'),
('ASIN'),
('EAN'),
('UPC'),
('GTIN');

insert into amazon_home_improvement.valid_capacity_name values
('20'),
('200 bpm'),
('2-1/4 Inches at 45 Degrees'),
('150 psi'),
('20 Milimeters'),
('34 Degree/110 Nails'),
('1/2 inch in wood'),
('3-1/8 Inch'),
('1-3/4 Inches'),
('20 Inches'),
('18 inches in tile');

insert into amazon_home_improvement.valid_flush_type values
('Electronic'),
('Automatic'),
('Dual');

insert into amazon_home_improvement.valid_temperature_range_unit_of_measure values
('degrees-fahrenheit'),
('degrees-celsius');

insert into amazon_home_improvement.valid_spout_height_unit_of_measure values
('FT'),
('CM'),
('MM'),
('M'),
('Gauge'),
('IN');

insert into amazon_home_improvement.valid_cpsia_cautionary_statement values
('no_warning_applicable'),
('choking_hazard_contains_a_marble'),
('contains_small_magnets'),
('choking_hazard_is_a_marble'),
('choking_hazard_balloon'),
('choking_hazard_small_parts'),
('choking_hazard_contains_small_ball'),
('choking_hazard_is_a_small_ball');

insert into amazon_home_improvement.valid_item_thickness_unit_of_measure values
('FT'),
('CM'),
('MM'),
('M'),
('Gauge'),
('IN');

insert into amazon_home_improvement.valid_item_torque_unit_of_measure values
('inch_pounds'),
('newton_millimeters'),
('foot_pounds'),
('centimeter_kilograms'),
('newtons'),
('kilonewtons'),
('newton_meters'),
('inch_ounces');

insert into amazon_home_improvement.valid_country_of_origin values
('Canada'),
('Guinea-Bissau'),
('Saint Helena'),
('Unknown'),
('Lithuania'),
('Cambodia'),
('Switzerland'),
('Ethiopia'),
('Aruba'),
('Swaziland'),
('Argentina'),
('Bolivia'),
('Cameroon'),
('Burkina Faso'),
('Turkmenistan'),
('Ghana'),
('Saudi Arabia'),
('Togo'),
('Japan'),
('Cape Verde'),
('Cocos (Keeling) Islands'),
('Slovenia'),
('Guatemala'),
('Bosnia and Herzegovina'),
('Kuwait'),
('Burma (Myanmar)'),
('Jordan'),
('Dominica'),
('Liberia'),
('Maldives'),
('Jamaica'),
('Oman'),
('Tanzania'),
('Martinique'),
('Saint Kitts And Nevis'),
('Ivory Coast'),
('Albania'),
('Gabon'),
('Niue'),
('Monaco'),
('Wallis and Futuna'),
('New Zealand'),
('Yemen'),
('Jersey'),
('Andorra'),
('Greenland'),
('Samoa'),
('Macau'),
('S. Georgia and S. Sandwich Isls.'),
('Norfolk Island'),
('United Arab Emirates'),
('Guam'),
('India'),
('Azerbaijan'),
('Lesotho'),
('Saint Vincent And The Grenadines'),
('Kenya'),
('South Korea'),
('Tajikistan'),
('Turkey'),
('Afghanistan'),
('Bangladesh'),
('Mauritania'),
('Solomon Islands'),
('Saint Lucia'),
('Hungary'),
('San Marino'),
('French Polynesia'),
('France'),
('Bermuda'),
('Slovakia'),
('Somalia'),
('Peru'),
('Laos'),
('Nauru'),
('Seychelles'),
('Norway'),
('Malawi'),
('Cook Islands'),
('Benin'),
('Western Sahara'),
('Cuba'),
('Republic of the Congo'),
('Mayotte'),
('China'),
('Armenia'),
('Dominican Republic'),
('Mongolia'),
('Ukraine'),
('Bahrain'),
('Tonga'),
('Finland'),
('Libya'),
('New Caledonia'),
('Cayman Islands'),
('Central African Republic'),
('Heard and McDonald Islands'),
('Mauritius'),
('Liechtenstein'),
('Australia'),
('Antigua And Barbuda'),
('Mali'),
('Russia'),
('Bulgaria'),
('United States'),
('Romania'),
('Angola'),
('French Southern Territories'),
('Chad'),
('South Africa'),
('Tokelau'),
('Cyprus'),
('Sweden'),
('Qatar'),
('Malaysia'),
('Austria'),
('Vietnam'),
('Mozambique'),
('Uganda'),
('Canary Islands'),
('British Virgin Islands'),
('Niger'),
('Isle of Man'),
('Brazil'),
('Turks And Caicos Islands'),
('Falkland Islands'),
('Faroe Islands'),
('Guinea'),
('Panama'),
('Costa Rica'),
('Luxembourg'),
('American Samoa'),
('Bahamas'),
('Gibraltar'),
('Ireland'),
('Pakistan'),
('Palau'),
('Nigeria'),
('Ecuador'),
('Czech Republic'),
('US Virgin Islands'),
('Brunei'),
('Belarus'),
('Iran'),
('Algeria'),
('Svalbard'),
('El Salvador'),
('Tuvalu'),
('Zaire'),
('Pitcairn Islands'),
('Saint Pierre and Miquelon'),
('Marshall Islands'),
('Chile'),
('Puerto Rico'),
('Belgium'),
('Kiribati'),
('Haiti'),
('Belize'),
('Hong Kong'),
('Sierra Leone'),
('Georgia'),
('Gambia'),
('Philippines'),
('Sao Tome And Principe'),
('Moldova'),
('Holy See (Vatican City)'),
('Croatia'),
('Micronesia'),
('Guernsey'),
('Thailand'),
('Namibia'),
('Grenada'),
('Iraq'),
('Portugal'),
('Estonia'),
('Uruguay'),
('Equatorial Guinea'),
('Lebanon'),
('Uzbekistan'),
('Tunisia'),
('Djibouti'),
('Rwanda'),
('Timor-Leste'),
('Spain'),
('Colombia'),
('Reunion'),
('Burundi'),
('Taiwan'),
('Fiji'),
('Barbados'),
('Madagascar'),
('Italy'),
('Bhutan'),
('Sudan'),
('Nepal'),
('Malta'),
('Democratic Republic of the Congo'),
('Netherlands'),
('Northern Mariana Islands'),
('Suriname'),
('Anguilla'),
('Venezuela'),
('Netherlands Antilles'),
('Aland Islands'),
('Israel'),
('Indonesia'),
('Iceland'),
('Zambia'),
('Senegal'),
('Papua New Guinea'),
('Zimbabwe'),
('Germany'),
('Vanuatu'),
('Denmark'),
('Saint-Martin'),
('Kazakhstan'),
('Poland'),
('Eritrea'),
('Kyrgyzstan'),
('Palestinian Territory'),
('British Indian Ocean Territory'),
('Montserrat'),
('Mexico'),
('Macedonia'),
('North Korea'),
('Sri Lanka'),
('Latvia'),
('Guyana'),
('Syria'),
('Guadeloupe'),
('Morocco'),
('Honduras'),
('Bouvet Island'),
('Egypt'),
('Nicaragua'),
('Singapore'),
('Serbia'),
('Botswana'),
('United Kingdom'),
('Trinidad And Tobago'),
('Antarctica'),
('Christmas Island'),
('Greece'),
('Paraguay'),
('French Guiana'),
('Comoros'),
('US Minor Outlying Islands');

insert into amazon_home_improvement.valid_special_features values
('Washable'),
('Contact Points'),
('Rechargeable Battery'),
('Quiet Close'),
('Self Tightening'),
('Removable'),
('Horizontal Spray'),
('Carbide Height'),
('Positive Stop'),
('Rainfall'),
('Keyless Features'),
('Electrode Thickness 1/4-Inch'),
('Extra Height'),
('20-Degree Wire Colated'),
('Variable Speed'),
('Outlets'),
('Batch Feed Disposal'),
('Vertical Cleansing'),
('Paintable'),
('Variable Speed Dial'),
('Air Inlet Thread Size (NPT)'),
('Lockable'),
('Massaging Head'),
('Dust Collection'),
('Adjustable Shoe'),
('Dust Cycle Time'),
('Velcro'),
('Quiet'),
('Diode 635-Nanometers'),
('Latch Throw'),
('28-Degree Plastic Coated'),
('Electrode Type: Copper'),
('Wheels'),
('Hose Size'),
('Adjustable'),
('Portable'),
('Dust Cycle Percentage'),
('Recirculating'),
('Magnetic'),
('Waterproof'),
('Impact Resistance'),
('Rim Wash'),
('Electrode Type: Mild Steel'),
('Heated Seats'),
('Orbital Action'),
('32-Degree Paper Colated'),
('Electric Brake'),
('Easy to Install');

insert into amazon_home_improvement.valid_measurement_system values
('English/Standard'),
('Metric');

insert into amazon_home_improvement.valid_extension_length_unit_of_measure values
('FT'),
('CM'),
('MM'),
('M'),
('Gauge'),
('IN');

insert into amazon_home_improvement.valid_maximum_power_unit_of_measure values
('watts'),
('kilowatts');

insert into amazon_home_improvement.valid_item_display_height_unit_of_measure values
('FT'),
('CM'),
('MM'),
('M'),
('Gauge'),
('IN');

insert into amazon_home_improvement.valid_strand_diameter_unit_of_measure values
('FT'),
('CM'),
('MM'),
('M'),
('Gauge'),
('IN');

insert into amazon_home_improvement.valid_thread_pitch_string values
('Large'),
('Qlock'),
('Small');

