insert into amazon_jewelry.valid_inscription values
('girdle'),
('setting'),
('NO');

insert into amazon_jewelry.valid_item_dimensions_unit_of_measure values
('FT'),
('CM'),
('MM'),
('M'),
('IN');

insert into amazon_jewelry.valid_package_dimensions_unit_of_measure values
('FT'),
('CM'),
('MM'),
('M'),
('IN');

insert into amazon_jewelry.valid_is_resizable values
('True'),
('False');

insert into amazon_jewelry.valid_material_type values
('shell'),
('synthetic-resin'),
('enamel'),
('glass'),
('leather'),
('coral'),
('ceramic'),
('pearl'),
('resin'),
('rhinestone'),
('rubber'),
('crystal'),
('wood'),
('epoxy'),
('bamboo'),
('mother-of-pearl');

insert into amazon_jewelry.valid_currency values
('USD');

insert into amazon_jewelry.valid_cpsia_cautionary_statement values
('no_warning_applicable'),
('choking_hazard_contains_a_marble'),
('contains_small_magnets'),
('choking_hazard_is_a_marble'),
('choking_hazard_balloon'),
('choking_hazard_small_parts'),
('choking_hazard_contains_small_ball'),
('choking_hazard_is_a_small_ball');

insert into amazon_jewelry.valid_relationship_type values
('Variation'),
('Accessory');

insert into amazon_jewelry.valid_website_shipping_weight_unit_of_measure values
('LB'),
('KG'),
('GR'),
('OZ');

insert into amazon_jewelry.valid_is_lab_created values
('True'),
('False');

insert into amazon_jewelry.valid_total_diamond_weight_unit_of_measure values
('MG'),
('LB'),
('GR'),
('DWT'),
('CARATS'),
('OZ'),
('KG');

insert into amazon_jewelry.valid_pearl_type values
('chinese-freshwater-cultured'),
('multiple'),
('mabe-cultured'),
('akoya-cultured'),
('majorca-cultured'),
('biwa-cultured'),
('natural-pearl'),
('hybrid-cultured'),
('south-sea-baroque-cultured'),
('tahitian-cultured'),
('keshi-cultured'),
('south-sea-cultured'),
('freshwater-cultured'),
('simulated-pearl');

insert into amazon_jewelry.valid_display_dimensions_unit_of_measure values
('FT'),
('CM'),
('MM'),
('M'),
('IN');

insert into amazon_jewelry.valid_external_product_id_type values
('GCID'),
('GTIN'),
('UPC'),
('EAN');

insert into amazon_jewelry.valid_certificate_type values
('AGS'),
('IGI'),
('GIA');

insert into amazon_jewelry.valid_gem_type values
('created-ruby'),
('black-diamond'),
('padparadscha'),
('brown-diamond'),
('tiger-eye'),
('fire-opal'),
('green-amber'),
('rhodonite'),
('pyrope-garnet'),
('fire-citrine'),
('tourmaline'),
('larimar'),
('demantoid-garnet'),
('caribbean-amber'),
('iron-pyrite'),
('created-blue-sapphire'),
('malachite'),
('sodalite'),
('green-sapphire'),
('garnet'),
('alexandrite'),
('dyed-howlite'),
('quartzite'),
('turquoise'),
('created-alexandrite'),
('ammolite'),
('boulder-opal'),
('madeira-citrine'),
('green-tourmaline'),
('tashmarine-diopside'),
('hickoryite'),
('tanzanite'),
('jadeite'),
('emerald'),
('medusa-quartz'),
('peridot'),
('paraiba-tourmaline'),
('serpentine'),
('diopside'),
('pink-diamond'),
('cherry-amber'),
('zandrite'),
('topaz'),
('london-blue-topaz'),
('created-amethyst'),
('yellow-diamond'),
('goldstone'),
('swedish-slag'),
('jade'),
('rhodochrosite'),
('prasiolite-quartz'),
('moldovite'),
('lemon-quartz'),
('yellow-topaz'),
('hermatine'),
('smoky-topaz'),
('swiss-blue-topaz'),
('rubellite-tourmaline'),
('created-garnet'),
('rutilated-quartz'),
('zoisite'),
('amethyst'),
('created-peridot'),
('blue-chalcedony'),
('calcite'),
('created-emerald'),
('black-opal'),
('apatite'),
('hiddenite'),
('andradite-garnet'),
('grossular-garnet'),
('red-diamond'),
('blue-opal'),
('carnelian'),
('ametrine'),
('green-chalcedony'),
('hematite'),
('charoite'),
('rhodolite-garnet'),
('brazanite'),
('chrysoberyl'),
('amblygonite'),
('spessartite-garnet'),
('spinel'),
('scapolite'),
('cinnabar'),
('blue-topaz'),
('moonstone'),
('labradorite'),
('diaspore'),
('gaspeite'),
('danburite'),
('magnasite'),
('green-quartz'),
('amber'),
('paraiba'),
('green-garnet'),
('white-agate'),
('celestite'),
('watermelon-tourmaline'),
('amazonite'),
('cubic-zirconia'),
('golden-topaz'),
('pink-amethyst'),
('jasper'),
('hauyne'),
('mint-tourmaline'),
('purple-jade'),
('moissanite'),
('green-gold'),
('pink-topaz'),
('jet'),
('multi-color-amber'),
('mandarin-garnet'),
('citrine'),
('aquamarine'),
('kunzite'),
('blue-amber'),
('howlite'),
('copper-sunstone'),
('sphalerite'),
('pezzottaite'),
('hessonite'),
('prehnite'),
('onyx'),
('sphene'),
('yttrium-aluminium-garnet'),
('white-topaz'),
('petalite'),
('ouro-verde-quartz'),
('red-agate'),
('indicolite-tourmaline'),
('sea-blue-chalcedony'),
('created-yellow-sapphire'),
('ruby'),
('created-quartz'),
('champagne-diamond'),
('multi'),
('orange-agate'),
('blue-diamond'),
('aventurine'),
('heliodor'),
('lapis-lazuli'),
('sapphire'),
('smoky-quartz'),
('honey-amber'),
('agate'),
('star-sapphire'),
('opal'),
('paraiba-topaz'),
('created-white-sapphire'),
('created-sapphire'),
('botswana-agate'),
('fluorite'),
('almandite-garnet'),
('blue-zircon'),
('azurite'),
('blue-agate'),
('tsavorite'),
('yellow-scapolite'),
('bloodstone'),
('indicolite'),
('orange-chalcedony'),
('morganite'),
('sunstone-feldspar'),
('created-padparadscha'),
('created-opal'),
('zircon-gemstone'),
('beryl'),
('imperial-topaz'),
('rose-de-france'),
('stabilized-turquoise'),
('pink-chalcedony'),
('sardonyx'),
('rose-quartz'),
('quartzofe'),
('drusy-quartz'),
('white-sapphire'),
('rubelite'),
('quartz'),
('chrysoprase'),
('cats-eye'),
('marcasite'),
('created-aquamarine'),
('dumortierite'),
('strontium-titanate'),
('inclusion-citrine'),
('created-topaz'),
('lavender-chalcedony'),
('white-diamond'),
('mystic-topaz'),
('chalcedony'),
('created-pink-sapphire'),
('iolite'),
('kyanite'),
('pink-sapphire'),
('goshenite'),
('purple-spinel'),
('chrome-diopside'),
('pink-tourmaline'),
('pink-quartz'),
('green-amethyst'),
('synthetic-turquoise'),
('whiskey-diamond'),
('corundum'),
('obsidian'),
('butterscotch-amber'),
('fuschite'),
('andalusite'),
('shanseres'),
('blue-sapphire');

insert into amazon_jewelry.valid_product_tax_code values
('A_GEN_NOTAX');

insert into amazon_jewelry.valid_parent_child values
('parent'),
('child');

insert into amazon_jewelry.valid_stone_creation_method values
('synthetic'),
('natural'),
('simulated');

insert into amazon_jewelry.valid_metal_type values
('copper'),
('black-rhodium-plated-silver'),
('chocolate-gold'),
('rose-gold-flashed-silver'),
('yellow-gold-plated-bronze'),
('platinum-and-sterling-silver'),
('cobalt'),
('titanium'),
('platinum-plated'),
('gold-filled'),
('stainless-steel'),
('titanium-and-platinum'),
('platinum-and-white-gold'),
('yellow-gold'),
('platinum'),
('vermeil'),
('green-gold'),
('gold-foiled'),
('rose-and-yellow-gold'),
('titanium-and-stainless-steel'),
('titanium-and-gold'),
('rhodium-plated-base-metal'),
('white-and-yellow-gold'),
('rhodium-plated-brass'),
('bonded-gold-and-silver'),
('rhodium-plated-silver'),
('tri-color-gold'),
('white-gold-plated-silver'),
('silver-and-stainless-steel'),
('tungsten'),
('rose-gold'),
('rhodium-flashed-silver'),
('two-tone-silver-and-gold-plated'),
('yellow-gold-plated-silver'),
('nickel'),
('rhodium-plated-yellow-gold'),
('silver-plated-bronze'),
('yellow-gold-flashed-silver'),
('white-gold'),
('rhodium-plated-white-gold'),
('gold-plated-copper'),
('base'),
('rhodium-plated-gold'),
('rose-gold-and-sterling-silver'),
('brass'),
('platinum-plated-silver'),
('palladium'),
('no-metal-type'),
('bronze'),
('rhodium-plated-bronze'),
('rose-and-white-gold'),
('rose-gold-plated-base'),
('stainless-steel-and-gold'),
('platinum-and-yellow-gold'),
('rhodium-plated-gold-and-silver'),
('gold-plated-base'),
('gold-plated-silver'),
('brass-plated-gold'),
('silver-plated-base'),
('platinum-flashed-silver'),
('titanium-and-silver'),
('pewter'),
('alloy'),
('yellow-gold-and-sterling-silver'),
('sterling-silver'),
('white-gold-and-sterling-silver');

insert into amazon_jewelry.valid_update_delete values
('Update'),
('PartialUpdate'),
('Delete');

insert into amazon_jewelry.valid_country_of_origin values
('Canada'),
('Guinea-Bissau'),
('Saint Helena'),
('Unknown'),
('Lithuania'),
('Cambodia'),
('Switzerland'),
('Ethiopia'),
('Aruba'),
('Swaziland'),
('Argentina'),
('Bolivia'),
('Cameroon'),
('Burkina Faso'),
('Turkmenistan'),
('Ghana'),
('Saudi Arabia'),
('Togo'),
('Japan'),
('Cape Verde'),
('Cocos (Keeling) Islands'),
('Slovenia'),
('Guatemala'),
('Bosnia and Herzegovina'),
('Kuwait'),
('Burma (Myanmar)'),
('Jordan'),
('Dominica'),
('Liberia'),
('Maldives'),
('Jamaica'),
('Oman'),
('Tanzania'),
('Martinique'),
('Saint Kitts And Nevis'),
('Ivory Coast'),
('Albania'),
('Gabon'),
('Niue'),
('Monaco'),
('Wallis and Futuna'),
('New Zealand'),
('Yemen'),
('Jersey'),
('Andorra'),
('Greenland'),
('Samoa'),
('Macau'),
('S. Georgia and S. Sandwich Isls.'),
('Norfolk Island'),
('United Arab Emirates'),
('Guam'),
('India'),
('Azerbaijan'),
('Lesotho'),
('Saint Vincent And The Grenadines'),
('Kenya'),
('South Korea'),
('Tajikistan'),
('Turkey'),
('Afghanistan'),
('Bangladesh'),
('Mauritania'),
('Solomon Islands'),
('Saint Lucia'),
('Hungary'),
('San Marino'),
('French Polynesia'),
('France'),
('Bermuda'),
('Slovakia'),
('Somalia'),
('Peru'),
('Laos'),
('Nauru'),
('Seychelles'),
('Norway'),
('Malawi'),
('Cook Islands'),
('Benin'),
('Western Sahara'),
('Cuba'),
('Republic of the Congo'),
('Mayotte'),
('China'),
('Armenia'),
('Dominican Republic'),
('Mongolia'),
('Ukraine'),
('Bahrain'),
('Tonga'),
('Finland'),
('Libya'),
('New Caledonia'),
('Cayman Islands'),
('Central African Republic'),
('Heard and McDonald Islands'),
('Mauritius'),
('Liechtenstein'),
('Australia'),
('Antigua And Barbuda'),
('Mali'),
('Russia'),
('Bulgaria'),
('United States'),
('Romania'),
('Angola'),
('French Southern Territories'),
('Chad'),
('South Africa'),
('Tokelau'),
('Cyprus'),
('Sweden'),
('Qatar'),
('Malaysia'),
('Austria'),
('Vietnam'),
('Mozambique'),
('Uganda'),
('Canary Islands'),
('British Virgin Islands'),
('Niger'),
('Isle of Man'),
('Brazil'),
('Turks And Caicos Islands'),
('Falkland Islands'),
('Faroe Islands'),
('Guinea'),
('Panama'),
('Costa Rica'),
('Luxembourg'),
('American Samoa'),
('Bahamas'),
('Gibraltar'),
('Ireland'),
('Pakistan'),
('Palau'),
('Nigeria'),
('Ecuador'),
('Czech Republic'),
('US Virgin Islands'),
('Brunei'),
('Belarus'),
('Iran'),
('Algeria'),
('Svalbard'),
('El Salvador'),
('Tuvalu'),
('Zaire'),
('Pitcairn Islands'),
('Saint Pierre and Miquelon'),
('Marshall Islands'),
('Chile'),
('Puerto Rico'),
('Belgium'),
('Kiribati'),
('Haiti'),
('Belize'),
('Hong Kong'),
('Sierra Leone'),
('Georgia'),
('Gambia'),
('Philippines'),
('Sao Tome And Principe'),
('Moldova'),
('Holy See (Vatican City)'),
('Croatia'),
('Micronesia'),
('Guernsey'),
('Thailand'),
('Namibia'),
('Grenada'),
('Iraq'),
('Portugal'),
('Estonia'),
('Uruguay'),
('Equatorial Guinea'),
('Lebanon'),
('Uzbekistan'),
('Tunisia'),
('Djibouti'),
('Rwanda'),
('Timor-Leste'),
('Spain'),
('Colombia'),
('Reunion'),
('Burundi'),
('Taiwan'),
('Fiji'),
('Barbados'),
('Madagascar'),
('Italy'),
('Bhutan'),
('Sudan'),
('Nepal'),
('Malta'),
('Democratic Republic of the Congo'),
('Netherlands'),
('Northern Mariana Islands'),
('Suriname'),
('Anguilla'),
('Venezuela'),
('Netherlands Antilles'),
('Aland Islands'),
('Israel'),
('Indonesia'),
('Iceland'),
('Zambia'),
('Senegal'),
('Papua New Guinea'),
('Zimbabwe'),
('Germany'),
('Vanuatu'),
('Denmark'),
('Saint-Martin'),
('Kazakhstan'),
('Poland'),
('Eritrea'),
('Kyrgyzstan'),
('Palestinian Territory'),
('British Indian Ocean Territory'),
('Montserrat'),
('Mexico'),
('Macedonia'),
('North Korea'),
('Sri Lanka'),
('Latvia'),
('Guyana'),
('Syria'),
('Guadeloupe'),
('Morocco'),
('Honduras'),
('Bouvet Island'),
('Egypt'),
('Nicaragua'),
('Singapore'),
('Serbia'),
('Botswana'),
('United Kingdom'),
('Trinidad And Tobago'),
('Antarctica'),
('Christmas Island'),
('Greece'),
('Paraguay'),
('French Guiana'),
('Comoros'),
('US Minor Outlying Islands');

insert into amazon_jewelry.valid_feed_product_type values
('FashionNecklaceBraceletAnklet'),
('FineNecklaceBraceletAnklet'),
('FashionRing'),
('FashionEarring'),
('FineEarring'),
('FashionOther'),
('FineOther'),
('FineRing');

insert into amazon_jewelry.valid_total_gem_weight_unit_of_measure values
('MG'),
('LB'),
('GR'),
('DWT'),
('CARATS'),
('OZ'),
('KG');

insert into amazon_jewelry.valid_is_discontinued_by_manufacturer values
('True'),
('False');

insert into amazon_jewelry.valid_variation_theme values
('RingSize-TotalDiamondWeight'),
('ColorName'),
('MetalType'),
('MetalType-RingSize'),
('RingSize-SizePerPearl'),
('MetalType-TotalDiamondWeight'),
('MetalType-SizePerPearl'),
('RingSize'),
('SizePerPearl'),
('TotalDiamondWeight'),
('StyleName'),
('Length-SizePerPearl');

insert into amazon_jewelry.valid_stone_dimensions_unit_of_measure values
('MM'),
('CM'),
('IN');

insert into amazon_jewelry.valid_offering_can_be_giftwrapped values
('True'),
('False');

insert into amazon_jewelry.valid_total_metal_weight_unit_of_measure values
('MG'),
('LB'),
('GR'),
('DWT'),
('CARATS'),
('OZ'),
('KG');

insert into amazon_jewelry.valid_department_name values
('unisex-adult'),
('girls'),
('mens'),
('boys'),
('unisex-child'),
('womens');

insert into amazon_jewelry.valid_missing_keyset_reason values
('NonConsumer'),
('Specialized'),
('PrivateLabel'),
('PreConfigured');

insert into amazon_jewelry.valid_color_name values
('Blue'),
('Brown'),
('Purple'),
('Grey'),
('Yellow'),
('Green'),
('Pink'),
('Orange'),
('Black'),
('White'),
('Red');

insert into amazon_jewelry.valid_prop_65 values
('True'),
('False');

insert into amazon_jewelry.valid_package_weight_unit_of_measure values
('LB'),
('KG'),
('GR'),
('OZ');

insert into amazon_jewelry.valid_offering_can_be_gift_messaged values
('True'),
('False');

insert into amazon_jewelry.valid_fulfillment_center_id values
('DEFAULT'),
('AMAZON_NA');

