insert into amazon_music.valid_audio_encoding_language values
($$Vai$$),
($$Unknown$$),
($$Palauan$$),
($$Niuean$$),
($$Fanti$$),
($$latin_spanish$$),
($$Navaho$$),
($$Masai$$),
($$Bambara$$),
($$Sindhi$$),
($$Santali$$),
($$Duala$$),
($$Kirundi$$),
($$Votic$$),
($$Tsonga$$),
($$Kanuri$$),
($$Umbundu$$),
($$SalishanLanguages$$),
($$IranianLanguages$$),
($$Lahnda$$),
($$Hiligaynon$$),
($$Kachin$$),
($$MiddleHighGerman$$),
($$Pangasinan$$),
($$SouthernAltai$$),
($$CantoneseChinese$$),
($$Yiddish$$),
($$Ga$$),
($$Mossi$$),
($$Occitan$$),
($$Kawi$$),
($$FrenchCanadian$$),
($$Tonga$$),
($$Romance$$),
($$SichuanYi$$),
($$ScotsGaelic$$),
($$Konkani$$),
($$Nauru$$),
($$Sasak$$),
($$Assyrian$$),
($$Latin$$),
($$SerboCroatian$$),
($$KarenLanguages$$),
($$Georgian$$),
($$Aramaic$$),
($$Tigrinya$$),
($$Slovakian$$),
($$Tibetan$$),
($$SinoTibetan$$),
($$Ingush$$),
($$Nahautl$$),
($$Dzongkha$$),
($$Guarani$$),
($$Sidamo$$),
($$Batak$$),
($$Kurukh$$),
($$Herero$$),
($$Creek$$),
($$Greek$$),
($$Latvian$$),
($$English$$),
($$Mizo$$),
($$Croatian$$),
($$Chhattisgarhi$$),
($$Chinese$$),
($$Buryat$$),
($$Inuktitut$$),
($$Tatar$$),
($$Pali$$),
($$Inuktitun$$),
($$Yapese$$),
($$Arabic$$),
($$Venda$$),
($$Erzya$$),
($$Alsatian$$),
($$CaucasianLanguages$$),
($$Oriya$$),
($$Inupiaq$$),
($$Lojban$$),
($$SignLanguage$$),
($$Inupiak$$),
($$Hindi$$),
($$Ewondo$$),
($$Karelian$$),
($$KarachayBalkar$$),
($$AlgonquianLanguages$$),
($$Hungarian$$),
($$Wolof$$),
($$Bosnian$$),
($$Vietnamese$$),
($$LubaLulua$$),
($$Afrihili$$),
($$Castillian$$),
($$ClassicalSyriac$$),
($$Hokkien$$),
($$JudeoArabic$$),
($$AfroAsiaticLanguages$$),
($$Kazakh$$),
($$Tiv$$),
($$NorwegianBokmal$$),
($$Angika$$),
($$KhoisanLanguages$$),
($$Braj$$),
($$MiddleDutch$$),
($$Mirandese$$),
($$German$$),
($$Lezghian$$),
($$Basque$$),
($$Tumbuka$$),
($$Mandar$$),
($$LowGerman$$),
($$Chechen$$),
($$Nzima$$),
($$Dutch$$),
($$Sanskrit$$),
($$Ekajuk$$),
($$Grebo$$),
($$Bihari$$),
($$Welsh$$),
($$NorthNdebele$$),
($$NorthernSami$$),
($$Gondi$$),
($$Bashkir$$),
($$Kamba$$),
($$Tamashek$$),
($$kumaoni$$),
($$Gwichin$$),
($$Makasar$$),
($$ClassicalNewari$$),
($$Interlingua$$),
($$Japanese$$),
($$Kinyarwanda$$),
($$Interlingue$$),
($$Hebrew$$),
($$Esperanto$$),
($$Austronesian$$),
($$Sami$$),
($$Nyamwezi$$),
($$Telugu$$),
($$TongaNyasa$$),
($$LubaKatanga$$),
($$Kokborok$$),
($$tulu$$),
($$Armenian$$),
($$Bodo$$),
($$Sandawe$$),
($$ChamicLanguages$$),
($$Tamil$$),
($$Kalaallisut$$),
($$OttomanTurkish$$),
($$gahrwali$$),
($$Gullah$$),
($$Gibberish$$),
($$Dinka$$),
($$Garo$$),
($$Romansch$$),
($$Lamba$$),
($$Micmac$$),
($$OldProvencal$$),
($$Indic$$),
($$Galician$$),
($$Madurese$$),
($$Kimbundu$$),
($$OldHighGerman$$),
($$Farsi$$),
($$Khasi$$),
($$Mandingo$$),
($$Marshallese$$),
($$SonghaiLanguages$$),
($$YupikLanguages$$),
($$Marathi$$),
($$Azerbaijani$$),
($$Luo$$),
($$Elamite$$),
($$Shan$$),
($$Adygei$$),
($$Norwegian$$),
($$Ganda$$),
($$EasternFrisian$$),
($$Komi$$),
($$Aragonese$$),
($$Yugoslavian$$),
($$Hittite$$),
($$Turkmen$$),
($$Zaza$$),
($$None$$),
($$Sukuma$$),
($$Aromanian$$),
($$SorbianLanguages$$),
($$TupiLanguages$$),
($$HiriMotu$$),
($$Bribri$$),
($$Flemish$$),
($$Tokelau$$),
($$Beja$$),
($$KaraKalpak$$),
($$FrenchCreole$$),
($$Kabyle$$),
($$Gothic$$),
($$PigLatin$$),
($$Pedi$$),
($$Swahili$$),
($$Cherokee$$),
($$Pashto$$),
($$Yao$$),
($$Bliss$$),
($$Magahi$$),
($$Malagasy$$),
($$Tlingit$$),
($$Slavic$$),
($$Maori$$),
($$Catalan$$),
($$Igbo$$),
($$Ladino$$),
($$Luxembourgish$$),
($$Serer$$),
($$Phoenician$$),
($$PapuanLanguages$$),
($$Selkup$$),
($$Bini$$),
($$Baluchi$$),
($$MundaLanguages$$),
($$Rajasthani$$),
($$Hausa$$),
($$Moldavian$$),
($$SemiticLanguages$$),
($$Kumyk$$),
($$AthapascanLanguages$$),
($$Avaric$$),
($$Chuukese$$),
($$Uighur$$),
($$Mapudungun$$),
($$IjoLanguages$$),
($$Setswana$$),
($$Maithili$$),
($$TokPisin$$),
($$SiouanLanguages$$),
($$SouthernSami$$),
($$SwissGerman$$),
($$BandaLanguages$$),
($$Balinese$$),
($$Dogri$$),
($$Egyptian$$),
($$Cayuga$$),
($$Tuvinian$$),
($$Cree$$),
($$Rarotongan$$),
($$Maltese$$),
($$Assamese$$),
($$Samaritan$$),
($$Jula$$),
($$Coptic$$),
($$SkoltSami$$),
($$Frisian$$),
($$Portuguese$$),
($$Achinese$$),
($$Tereno$$),
($$OldIrish$$),
($$Kalmyk$$),
($$Avestan$$),
($$OldSlavonic$$),
($$Minangkabau$$),
($$Pampanga$$),
($$BamilekeLanguages$$),
($$ChinookJargon$$),
($$Cornish$$),
($$Bulgarian$$),
($$Moksha$$),
($$CrimeanTatar$$),
($$Yoruba$$),
($$Arawak$$),
($$Nyankole$$),
($$French$$),
($$JudeoPersian$$),
($$WakashanLanguages$$),
($$Bengali$$),
($$Basa$$),
($$Haitian$$),
($$Nepali$$),
($$Finnish$$),
($$Udmurt$$),
($$Sundanese$$),
($$Albanian$$),
($$Osage$$),
($$NiloSaharanLanguages$$),
($$Tagalog$$),
($$Serbian$$),
($$Italian$$),
($$Luiseno$$),
($$Chibcha$$),
($$Walloon$$),
($$MiddleEnglish$$),
($$Chamorro$$),
($$Amharic$$),
($$Tajik$$),
($$Rapanui$$),
($$ArtificialLanguages$$),
($$Urdu$$),
($$Lozi$$),
($$Gorontalo$$),
($$Chagatai$$),
($$Lapp$$),
($$OldNorse$$),
($$Waray$$),
($$Nias$$),
($$Kutenai$$),
($$Fulah$$),
($$Buginese$$),
($$Cheyenne$$),
($$Fon$$),
($$Awadhi$$),
($$GalibiCarib$$),
($$Indonesian$$),
($$Chiricahua$$),
($$Hawaiian$$),
($$KruLanguages$$),
($$Dhivehi$$),
($$Chichewa$$),
($$Sinhalese$$),
($$Adangme$$),
($$Thai$$),
($$Afrikaans$$),
($$MonKhmerLanguages$$),
($$Ugaritic$$),
($$Uzbek$$),
($$ManoboLanguages$$),
($$Zenaga$$),
($$Limburgan$$),
($$Slovak$$),
($$Burmese$$),
($$Aleut$$),
($$Lingala$$),
($$OtomianLanguages$$),
($$IndoEuropean$$),
($$Syriac$$),
($$NigerKordofanianLanguages$$),
($$Friulian$$),
($$Nyoro$$),
($$MiddleFrench$$),
($$Breton$$),
($$Turkish$$),
($$Zulu$$),
($$Delaware$$),
($$TaiwaneseChinese$$),
($$Soninke$$),
($$MiddleIrish$$),
($$Zapotec$$),
($$Hmong$$),
($$Khmer$$),
($$Chuvash$$),
($$Lithuanian$$),
($$Sangho$$),
($$Malay$$),
($$Tzeltal$$),
($$Zuni$$),
($$Iban$$),
($$AltaicLanguages$$),
($$Cebuano$$),
($$Pohnpeian$$),
($$Berber$$),
($$Mohawk$$),
($$Dogrib$$),
($$Ukrainian$$),
($$Javanese$$),
($$AustralianLanguages$$),
($$UpperSorbian$$),
($$LowerSorbian$$),
($$HimachaliLanguages$$),
($$Kannada$$),
($$Persian$$),
($$Mongolian$$),
($$Choctaw$$),
($$Aymara$$),
($$Fiji$$),
($$Shona$$),
($$Chipewyan$$),
($$Corsican$$),
($$Kpelle$$),
($$ApacheLanguages$$),
($$NorthernFrisian$$),
($$Somali$$),
($$PortugueseBrazilian$$),
($$Arapaho$$),
($$GermanicLanguages$$),
($$Akan$$),
($$Lushai$$),
($$CelticLanguages$$),
($$Tahitian$$),
($$Gallegan$$),
($$Siksika$$),
($$LuleSami$$),
($$Dargwa$$),
($$Sogdian$$),
($$Gayo$$),
($$Ukranian$$),
($$BalticLanguages$$),
($$Kuanyama$$),
($$Asturian$$),
($$unqualified$$),
($$ZandeLanguages$$),
($$Oromo$$),
($$CushiticLanguages$$),
($$SouthernSotho$$),
($$Khotanese$$),
($$Neapolitan$$),
($$Bemba$$),
($$Blin$$),
($$Quechua$$),
($$Estonian$$),
($$Fang$$),
($$Byelorussian$$),
($$OldPersian$$),
($$Iloko$$),
($$Sesotho$$),
($$SlaveAthapascan$$),
($$Samoan$$),
($$Filipino$$),
($$Manx$$),
($$AmericanSignLanguage$$),
($$Kosraean$$),
($$Malayalam$$),
($$Efik$$),
($$Bantu$$),
($$Mongo$$),
($$Bislama$$),
($$Kongo$$),
($$Acoli$$),
($$Timne$$),
($$Papiamento$$),
($$Marwari$$),
($$Dakota$$),
($$Polish$$),
($$DravidianLanguages$$),
($$Kirghiz$$),
($$Bikol$$),
($$PortugueseCreole$$),
($$Swedish$$),
($$Ainu$$),
($$IroquoianLanguages$$),
($$Mayan$$),
($$Mari$$),
($$Ewe$$),
($$Faroese$$),
($$Danish$$),
($$Klingon$$),
($$Tetum$$),
($$Pahlavi$$),
($$SouthNdebele$$),
($$Gbaya$$),
($$Gilbertese$$),
($$Slovene$$),
($$Kikuyu$$),
($$SouthAmericanIndian$$),
($$PrakritLanguages$$),
($$Punjabi$$),
($$Tigre$$),
($$Bhojpuri$$),
($$Tsimshian$$),
($$Nogai$$),
($$Bhutani$$),
($$Yakut$$),
($$Sumerian$$),
($$AncientGreek$$),
($$Xhosa$$),
($$Manipuri$$),
($$NorthAmericanIndianLanguages$$),
($$Hupa$$),
($$Icelandic$$),
($$InariSami$$),
($$Twi$$),
($$OldFrench$$),
($$Greenlandic$$),
($$Gujarati$$),
($$Akkadian$$),
($$Kashubian$$),
($$Korean$$),
($$Creole$$),
($$Multilingual$$),
($$Nko$$),
($$Manchu$$),
($$Caddo$$),
($$FinnoUgrian$$),
($$MandarinChinese$$),
($$Kashmiri$$),
($$Siswati$$),
($$Haida$$),
($$Russian$$),
($$OldEnglish$$),
($$Afar$$),
($$Romany$$),
($$NubianLanguages$$),
($$Irish$$),
($$CentralAmericanIndianLanguages$$),
($$Sicilian$$),
($$Czech$$),
($$Kabardian$$),
($$Macedonian$$),
($$NorwegianNynorsk$$),
($$Lunda$$),
($$NepalBhasa$$),
($$haryanvi$$),
($$SrananTongo$$),
($$AfghanPashtu$$),
($$Romanian$$),
($$Sardinian$$),
($$Lao$$),
($$Dari$$),
($$Mende$$),
($$Ojibwa$$),
($$Washo$$),
($$PhilippineLanguages$$),
($$Kurdish$$),
($$LandDayakLanguages$$),
($$Walamo$$),
($$Geez$$),
($$GaelicScots$$),
($$Zhuang$$),
($$Ido$$),
($$Volapuk$$),
($$TaiLanguages$$),
($$Tuvalu$$),
($$Abkhazian$$),
($$Ndonga$$),
($$Scots$$),
($$Susu$$),
($$Cambodian$$),
($$Spanish$$),
($$Ossetian$$);

insert into amazon_music.valid_country_of_origin values
($$Canada$$),
($$Guinea-Bissau$$),
($$Saint Helena$$),
($$Unknown$$),
($$Lithuania$$),
($$Cambodia$$),
($$Switzerland$$),
($$Ethiopia$$),
($$Aruba$$),
($$Swaziland$$),
($$Argentina$$),
($$Bolivia$$),
($$Cameroon$$),
($$Burkina Faso$$),
($$Turkmenistan$$),
($$Ghana$$),
($$Saudi Arabia$$),
($$Togo$$),
($$Japan$$),
($$Cape Verde$$),
($$Cocos (Keeling) Islands$$),
($$Slovenia$$),
($$Guatemala$$),
($$Bosnia and Herzegovina$$),
($$Kuwait$$),
($$Burma (Myanmar)$$),
($$Jordan$$),
($$Dominica$$),
($$Liberia$$),
($$Maldives$$),
($$Jamaica$$),
($$Oman$$),
($$Tanzania$$),
($$Martinique$$),
($$Saint Kitts And Nevis$$),
($$Ivory Coast$$),
($$Albania$$),
($$Gabon$$),
($$Niue$$),
($$Monaco$$),
($$Wallis and Futuna$$),
($$New Zealand$$),
($$Yemen$$),
($$Jersey$$),
($$Andorra$$),
($$Greenland$$),
($$Samoa$$),
($$Macau$$),
($$S. Georgia and S. Sandwich Isls.$$),
($$Norfolk Island$$),
($$United Arab Emirates$$),
($$Guam$$),
($$India$$),
($$Azerbaijan$$),
($$Lesotho$$),
($$Saint Vincent And The Grenadines$$),
($$Kenya$$),
($$South Korea$$),
($$Tajikistan$$),
($$Turkey$$),
($$Afghanistan$$),
($$Bangladesh$$),
($$Mauritania$$),
($$Solomon Islands$$),
($$Saint Lucia$$),
($$Hungary$$),
($$San Marino$$),
($$French Polynesia$$),
($$France$$),
($$Bermuda$$),
($$Slovakia$$),
($$Somalia$$),
($$Peru$$),
($$Laos$$),
($$Nauru$$),
($$Seychelles$$),
($$Norway$$),
($$Malawi$$),
($$Cook Islands$$),
($$Benin$$),
($$Western Sahara$$),
($$Cuba$$),
($$Republic of the Congo$$),
($$Mayotte$$),
($$China$$),
($$Armenia$$),
($$Dominican Republic$$),
($$Mongolia$$),
($$Ukraine$$),
($$Bahrain$$),
($$Tonga$$),
($$Finland$$),
($$Libya$$),
($$New Caledonia$$),
($$Cayman Islands$$),
($$Central African Republic$$),
($$Heard and McDonald Islands$$),
($$Mauritius$$),
($$Liechtenstein$$),
($$Australia$$),
($$Antigua And Barbuda$$),
($$Mali$$),
($$Russia$$),
($$Bulgaria$$),
($$United States$$),
($$Romania$$),
($$Angola$$),
($$French Southern Territories$$),
($$Chad$$),
($$South Africa$$),
($$Tokelau$$),
($$Cyprus$$),
($$Sweden$$),
($$Qatar$$),
($$Malaysia$$),
($$Austria$$),
($$Vietnam$$),
($$Mozambique$$),
($$Uganda$$),
($$Canary Islands$$),
($$British Virgin Islands$$),
($$Niger$$),
($$Isle of Man$$),
($$Brazil$$),
($$Turks And Caicos Islands$$),
($$Falkland Islands$$),
($$Faroe Islands$$),
($$Guinea$$),
($$Panama$$),
($$Costa Rica$$),
($$Luxembourg$$),
($$American Samoa$$),
($$Bahamas$$),
($$Gibraltar$$),
($$Ireland$$),
($$Pakistan$$),
($$Palau$$),
($$Nigeria$$),
($$Ecuador$$),
($$Czech Republic$$),
($$US Virgin Islands$$),
($$Brunei$$),
($$Belarus$$),
($$Iran$$),
($$Algeria$$),
($$Svalbard$$),
($$El Salvador$$),
($$Tuvalu$$),
($$Zaire$$),
($$Pitcairn Islands$$),
($$Saint Pierre and Miquelon$$),
($$Marshall Islands$$),
($$Chile$$),
($$Puerto Rico$$),
($$Belgium$$),
($$Kiribati$$),
($$Haiti$$),
($$Belize$$),
($$Hong Kong$$),
($$Sierra Leone$$),
($$Georgia$$),
($$Gambia$$),
($$Philippines$$),
($$Sao Tome And Principe$$),
($$Moldova$$),
($$Holy See (Vatican City)$$),
($$Croatia$$),
($$Micronesia$$),
($$Guernsey$$),
($$Thailand$$),
($$Namibia$$),
($$Grenada$$),
($$Iraq$$),
($$Portugal$$),
($$Estonia$$),
($$Uruguay$$),
($$Equatorial Guinea$$),
($$Lebanon$$),
($$Uzbekistan$$),
($$Tunisia$$),
($$Djibouti$$),
($$Rwanda$$),
($$Timor-Leste$$),
($$Spain$$),
($$Colombia$$),
($$Reunion$$),
($$Burundi$$),
($$Taiwan$$),
($$Fiji$$),
($$Barbados$$),
($$Madagascar$$),
($$Italy$$),
($$Bhutan$$),
($$Sudan$$),
($$Nepal$$),
($$Malta$$),
($$Democratic Republic of the Congo$$),
($$Netherlands$$),
($$Northern Mariana Islands$$),
($$Suriname$$),
($$Anguilla$$),
($$Venezuela$$),
($$Netherlands Antilles$$),
($$Aland Islands$$),
($$Israel$$),
($$Indonesia$$),
($$Iceland$$),
($$Zambia$$),
($$Senegal$$),
($$Papua New Guinea$$),
($$Zimbabwe$$),
($$Germany$$),
($$Vanuatu$$),
($$Denmark$$),
($$Saint-Martin$$),
($$Kazakhstan$$),
($$Poland$$),
($$Eritrea$$),
($$Kyrgyzstan$$),
($$Palestinian Territory$$),
($$British Indian Ocean Territory$$),
($$Montserrat$$),
($$Mexico$$),
($$Macedonia$$),
($$North Korea$$),
($$Sri Lanka$$),
($$Latvia$$),
($$Guyana$$),
($$Syria$$),
($$Guadeloupe$$),
($$Morocco$$),
($$Honduras$$),
($$Bouvet Island$$),
($$Egypt$$),
($$Nicaragua$$),
($$Singapore$$),
($$Serbia$$),
($$Botswana$$),
($$United Kingdom$$),
($$Trinidad And Tobago$$),
($$Antarctica$$),
($$Christmas Island$$),
($$Greece$$),
($$Paraguay$$),
($$French Guiana$$),
($$Comoros$$),
($$US Minor Outlying Islands$$);

insert into amazon_music.valid_is_adult_product values
($$True$$),
($$False$$);

insert into amazon_music.valid_subject_keywords values
($$Classical - Classical Period - Chamber Music$$),
($$Soundtracks - Television Soundtracks$$),
($$Dance & DJ - Disco$$),
($$Pop - Singer-Songwriters$$),
($$Pop - Adult Contemporary Pop$$),
($$R&B Music - Soul$$),
($$Classical - Baroque Period - Concertos$$),
($$Classical - Modern Period - Vocal Music$$),
($$Folk Music - Traditional British Folk$$),
($$Country - Alt-Country$$),
($$Classical - Early Music - Concertos$$),
($$Latin Music - Mambo$$),
($$Rap - General$$),
($$Classical - Baroque Period - General$$),
($$Rock - Glam Rock$$),
($$International Music - African$$),
($$Latin Music - Latin Pop$$),
($$Classical - Classical Period - Opera$$),
($$Jazz - Jazz Fusion$$),
($$Classical - Romantic Period - General$$),
($$Jazz - Swing$$),
($$Classical - Classical Period - Concertos$$),
($$Rock - Indie Rock$$),
($$Rock - Death Metal$$),
($$Christian Music - Contemporary$$),
($$Classical - Romantic Period - Ballets & Dances$$),
($$Blues - Traditional$$),
($$Rock - Hardcore & Punk Rock$$),
($$Dance & DJ - General$$),
($$Dance & DJ - Trip-Hop$$),
($$Classical - Baroque Period - Symphonies$$),
($$Soundtracks - Movie Scores$$),
($$Classical - Renaissance Period - Ballets & Dances$$),
($$Classical - Romantic Period - Vocal Music$$),
($$Children's Music - Lullabies$$),
($$Classical - Early Music - General$$),
($$New Age - General$$),
($$Miscellaneous - Exercise$$),
($$Jazz - Vocal Jazz$$),
($$Classical - Renaissance Period - Symphonies$$),
($$Jazz - Bop Jazz$$),
($$Miscellaneous - Experimental$$),
($$R&B Music - Funk$$),
($$Classical - Renaissance Period - Concertos$$),
($$International Music - Middle Eastern$$),
($$Miscellaneous - Karaoke$$),
($$Classical - Early Music - Vocal Music$$),
($$Classical - Early Music - Symphonies$$),
($$Miscellaneous - General$$),
($$Classical - Modern Period - Symphonies$$),
($$Jazz - Smooth Jazz$$),
($$Rap - Southern Rap$$),
($$Jazz - Jazz$$),
($$Pop - Soft Rock$$),
($$International Music - Latin$$),
($$Classical - Romantic Period - Chamber Music$$),
($$Latin Music - Merengue$$),
($$R&B Music - Classic R&B$$),
($$Country - Traditional Country$$),
($$Soundtracks - Movie Soundtracks$$),
($$Blues - Electric$$),
($$Folk Music - General$$),
($$International Music - Australia & Oceania$$),
($$Latin Music - Tango$$),
($$Latin Music - General$$),
($$Pop - Vocal Pop$$),
($$Dance & DJ - Electronica$$),
($$Country - Bluegrass$$),
($$Miscellaneous - Instruction$$),
($$Pop - Easy Listening$$),
($$Dance & DJ - Ambient$$),
($$Country - Contemporary Country$$),
($$Classical - Early Music - Opera$$),
($$Classical - Renaissance Period - Vocal Music$$),
($$Soundtracks - General$$),
($$Classical - Romantic Period - Opera$$),
($$Pop - Pop Rock$$),
($$International Music - Central American$$),
($$Christian Music - Gospel$$),
($$Broadway & Vocal - Musicals$$),
($$Classical - Romantic Period - Symphonies$$),
($$Rock - New Wave$$),
($$Rock - Classic Rock$$),
($$Classical - Renaissance Period - Chamber Music$$),
($$Latin Music - Flamenco$$),
($$Classical - Modern Period - Ballets & Dances$$),
($$R&B Music - Contemporary R&B$$),
($$Jazz - Latin Jazz$$),
($$Jazz - Traditional Jazz$$),
($$R&B Music - General$$),
($$Classical - Modern Period - General$$),
($$Classical - Early Music - Chamber Music$$),
($$Christian Music - Alternative$$),
($$Children's Music - General$$),
($$Rock - Alternative Rock$$),
($$Rock - British Invasion Rock$$),
($$International Music - Caribbean$$),
($$Rap - Experimental Rap$$),
($$International Music - South American$$),
($$International Music - Reggae$$),
($$Classical - Renaissance Period - General$$),
($$Blues - Contemporary$$),
($$Rap - West Coast Rap$$),
($$Rock - Album-Oriented Rock$$),
($$Jazz - Avant Garde Jazz$$),
($$Christian Music - General$$),
($$Rap - East Coast Rap$$),
($$Folk Music - Contemporary Folk$$),
($$Folk Music - Traditional Irish Folk$$),
($$Christian Music - Praise and Worship$$),
($$Blues - General$$),
($$Classical - Modern Period - Concertos$$),
($$Pop - General$$),
($$Children's Music - Educational$$),
($$Rock - Psychedelic Rock$$),
($$Classical - Classical Period - Vocal Music$$),
($$New Age - Relaxation$$),
($$Rap - Rap & Hip-Hop$$),
($$Rap - Pop-Rap$$),
($$Broadway & Vocal - General$$),
($$Classical - Modern Period - Opera$$),
($$Classical - Renaissance Period - Opera$$),
($$Country - General$$),
($$Rock - Goth & Industrial Rock$$),
($$Rock - Southern Rock$$),
($$Jazz - General$$),
($$International Music - European$$),
($$Classical - Classical Period - Symphonies$$),
($$Classical - Classical Period - Ballets & Dances$$),
($$Folk Music - Jewish Folk$$),
($$International Music - General$$),
($$Pop - Dance Pop$$),
($$Classical - Baroque Period - Opera$$),
($$R&B Music - R&B$$),
($$Blues - Acoustic$$),
($$Latin Music - Mariachi$$),
($$Classical - Early Music - Ballets & Dances$$),
($$Classical - Romantic Period - Concertos$$),
($$Dance & DJ - Techno$$),
($$Classical - Classical Period - General$$),
($$Miscellaneous - Comedy$$),
($$New Age - Meditation$$),
($$Miscellaneous - Holiday$$),
($$Christian Music - Rock$$),
($$International Music - Asian$$),
($$Folk Music - Traditional Folk$$),
($$Classical - Modern Period - Chamber Music$$),
($$Rock - Hard Rock & Metal$$),
($$Classical - General$$),
($$Classical - Baroque Period - Chamber Music$$),
($$Classical - Baroque Period - Vocal Music$$),
($$Rock - General$$),
($$Jazz - Cool Jazz$$),
($$Classical - Baroque Period - Ballets & Dances$$),
($$Latin Music - Salsa$$),
($$Jazz - Free Jazz$$);

insert into amazon_music.valid_package_dimensions_unit_of_measure values
($$FT$$),
($$CM$$),
($$MM$$),
($$M$$),
($$IN$$);

insert into amazon_music.valid_expedited_shipping values
($$Next, International$$),
($$Domestic, International$$),
($$Domestic, Second$$),
($$Domestic, Next$$),
($$Domestic$$),
($$Domestic, Second, Next, Internationa$$),
($$Domestic, Next, International$$),
($$Domestic, Second, Next$$),
($$Next$$),
($$Second, International$$),
($$Second$$),
($$Second, Next$$),
($$International$$),
($$Second, Next, International$$),
($$Domestic, Second, International$$);

insert into amazon_music.valid_update_delete values
($$Update$$),
($$PartialUpdate$$),
($$Delete$$);

insert into amazon_music.valid_standard_plus values
($$Y$$),
($$N$$);

insert into amazon_music.valid_binding values
($$AudioCD$$),
($$DvdAudio$$),
($$VideoCD$$),
($$Cassette$$),
($$LpRecord$$);

insert into amazon_music.valid_feed_product_type values
($$MusicPopular$$),
($$MusicClassical$$);

insert into amazon_music.valid_external_product_id_type values
($$GCID$$),
($$ASIN$$),
($$EAN$$),
($$UPC$$),
($$GTIN$$);

insert into amazon_music.valid_condition_type values
($$UsedGood$$),
($$CollectibleGood$$),
($$UsedLikeNew$$),
($$UsedVeryGood$$),
($$CollectibleAcceptable$$),
($$New$$),
($$CollectibleLikeNew$$),
($$CollectibleVeryGood$$),
($$UsedAcceptable$$);

insert into amazon_music.valid_cpsia_cautionary_statement values
($$NoWarningApplicable$$),
($$ChokingHazardContainsAMarble$$),
($$ChokingHazardBalloon$$),
($$ChokingHazardSmallParts$$),
($$ChokingHazardIsASmallBall$$),
($$ContainsSmallMagnets$$),
($$ChokingHazardContainsSmallBall$$),
($$ChokingHazardIsAMarble$$);

insert into amazon_music.valid_package_weight_unit_of_measure values
($$LB$$),
($$KG$$),
($$GR$$),
($$OZ$$);

insert into amazon_music.valid_audio_encoding values
($$DolbyDigital2.0Mono$$),
($$DolbyDigitalEx$$),
($$Mlplossless$$),
($$Quadraphonic$$),
($$DolbyDigitalPlus$$),
($$DolbyDigita4.1$$),
($$DolbyDigita4.0$$),
($$DolbyDigita5.0$$),
($$DolbyDigital2.0Stereo$$),
($$Dts6.1Es$$),
($$Pcm$$),
($$DtsInteractive$$),
($$PcmStereo$$),
($$PcmMono$$),
($$DolbyTrueHd5_1$$),
($$5_1DisneyEnhancedHomeTheaterMix$$),
($$DolbyDigital2.0Surround$$),
($$ThxSurroundex$$),
($$Dts61Es$$),
($$Dts5.0$$),
($$Dts5.1$$),
($$DolbyDigital1.0$$),
($$Mpeg1_2.0$$),
($$DolbyDigita2.1$$),
($$DolbyDigita3.0$$),
($$DolbyDigital2.0$$),
($$DolbyTrueHd$$),
($$Stereo$$),
($$DolbyStereoAnalog$$),
($$DolbyDigital5.1Es$$),
($$Mono$$),
($$DtsEs$$),
($$DolbySurround$$),
($$DolbyDigital5.1Ex$$),
($$DolbyDigitalLive$$),
($$DolbyDigital6.1Ex$$),
($$DtsHdHighresAudio$$),
($$DolbyDigital5.1$$),
($$DolbyDigital6.1Es$$),
($$Pcm_24_Bit_96_Khz$$),
($$UnknownAudioEncoding$$),
($$DolbyDigitalPlus2_0$$),
($$Surround$$),
($$Dts6.1$$),
($$DolbyDigitalPlus5_1$$),
($$PcmSurround$$),
($$7_1DisneyEnhancedHomeTheaterMix$$),
($$DigitalAtrac$$),
($$Analog$$),
($$Mpeg2_5.1$$);

insert into amazon_music.valid_product_tax_code values
($$A_GEN_NOTAX$$);

insert into amazon_music.valid_fulfillment_center_id values
($$DEFAULT$$),
($$AMAZON_NA$$);

insert into amazon_music.valid_will_ship_internationally values
($$1$$),
($$Y$$),
($$2$$),
($$N$$);

insert into amazon_music.valid_vinyl_record_details values
($$12_single$$),
($$45$$),
($$other$$),
($$lp$$),
($$unknown$$),
($$ep$$),
($$78$$);

insert into amazon_music.valid_format values
($$ExtendedPlay$$),
($$LimitedCollectorsEdition$$),
($$ExtraTracks$$),
($$Bsides$$),
($$Live$$),
($$MaxiSingle$$),
($$Import$$),
($$CopyProtectedCd$$),
($$Cutout$$),
($$DoubleLp$$),
($$SpecialEdition$$),
($$Ringle$$),
($$CollectorsEdition$$),
($$Remixes$$),
($$DoubleCd$$),
($$DeluxeEdition$$),
($$Compilation$$),
($$OriginalRecording$$),
($$Reissued$$),
($$ExplicitLyrics$$),
($$CastRecording$$),
($$Studio$$),
($$HybridSacd$$),
($$Remastered$$),
($$BestOf$$),
($$Sacd$$),
($$Mp3Audio$$),
($$Cd-Single$$),
($$SpecialExtendedVersion$$),
($$GoldCd$$),
($$SpecialLimitedEdition$$),
($$CdAndDvd$$),
($$UkImport$$),
($$AuthorizedBootleg$$),
($$Clean$$),
($$Soundtrack$$),
($$ValuePrice$$),
($$Karaoke$$),
($$Restored$$),
($$DualDisc$$),
($$Classical$$),
($$Minidisc$$),
($$Cd$$),
($$BoxSet$$),
($$JpImport$$),
($$Enhanced$$),
($$Hi-Fidelity$$),
($$DigitalSound$$),
($$Dolby$$),
($$ShmCd$$),
($$LimitedEdition$$);

