insert into amazon_sports.valid_fit_type values
('semi-fitted'),
('medium-regular'),
('relaxed'),
('large-tall'),
('baggy'),
('extra-small'),
('small'),
('fitted');

insert into amazon_sports.valid_maximum_stride_length_unit_of_measure values
('FT'),
('CM'),
('MM'),
('M'),
('IN');

insert into amazon_sports.valid_pattern_type values
('Patterned'),
('Paisley'),
('Checkered'),
('String'),
('Solid'),
('Stripes'),
('Pique'),
('Plaid'),
('Polka Dots'),
('Eyelet'),
('Weave');

insert into amazon_sports.valid_lash_length_unit_of_measure values
('FT'),
('CM'),
('MM'),
('M'),
('IN');

insert into amazon_sports.valid_item_display_width_unit_of_measure values
('FT'),
('CM'),
('MM'),
('M'),
('IN');

insert into amazon_sports.valid_fuel_capacity_unit_of_measure values
('cup'),
('cc'),
('CID'),
('l'),
('ounce'),
('gallon');

insert into amazon_sports.valid_top_style values
('Strapless/Tube'),
('Tank'),
('Halter'),
('Triangle Tops'),
('One Shoulder'),
('Cami'),
('Button Down'),
('Bandeaux'),
('Racerback');

insert into amazon_sports.valid_memory_storage_capacity_unit_of_measure values
('KB'),
('TB'),
('GB'),
('MB');

insert into amazon_sports.valid_specific_uses_for_product values
('dry-environment'),
('Cargo'),
('freeride'),
('Taekwondo'),
('cross country'),
('Kung Fu'),
('saltwater'),
('alpine touring'),
('Permanent below deck'),
('Outfield'),
('horse'),
('Aikido'),
('Kempo Capoeira'),
('carve'),
('filet'),
('telemark'),
('warm-temperatures'),
('Tandem'),
('Softball'),
('Ninjutsu'),
('performance'),
('salmon-fishing'),
('cabin'),
('stock'),
('Catcher'),
('pike-fishing'),
('boning'),
('First base'),
('freestyle'),
('Child'),
('camper'),
('all mountain'),
('Karate'),
('bass-fishing'),
('all-temperatures'),
('Wet-or-dry-environment'),
('Wet-environment'),
('alpine'),
('moderate-temperatures'),
('Ju Jitsu'),
('Portable'),
('technical'),
('Infield'),
('cold-temperatures'),
('Permanent above deck'),
('tent');

insert into amazon_sports.valid_item_display_weight_unit_of_measure values
('LB'),
('KG'),
('GR'),
('OZ');

insert into amazon_sports.valid_handle_material values
('Ivory'),
('Shell'),
('micarta'),
('aluminum'),
('titanium'),
('anodized'),
('zytel'),
('Horn'),
('stag'),
('bead-blasted'),
('EVAFoamslidering'),
('carbon-fiber'),
('Bone'),
('g-10');

insert into amazon_sports.valid_website_shipping_weight_unit_of_measure values
('LB'),
('KG'),
('GR'),
('OZ');

insert into amazon_sports.valid_lithium_battery_packaging values
('batteries_contained_in_equipment'),
('batteries_only'),
('batteries_packed_with_equipment');

insert into amazon_sports.valid_shaft_style_type values
('goalie-shafts'),
('midfielder-shafts'),
('defender-shafts'),
('attacker-shafts');

insert into amazon_sports.valid_fabric_type values
('Canvas'),
('viscose'),
('lycraspandex'),
('straw'),
('velcro'),
('ploypropylene'),
('double-knit-fabric'),
('oxford'),
('Elasticized Fabric'),
('Acrylic'),
('thermolite'),
('satin'),
('rayon'),
('cotton'),
('cotton-poly-rib-knit'),
('carinessa'),
('tulle'),
('velvet'),
('poplin'),
('fiberglass'),
('tackle-twill'),
('Felt'),
('goose-down'),
('DriSilque'),
('plastic'),
('other'),
('olefin'),
('microfiber'),
('net'),
('organza'),
('virgin-wool'),
('Corduroy'),
('foam'),
('cotton-poly-jersey'),
('Fleece'),
('100-percent-cotton-rib-knit'),
('worsted'),
('latex'),
('taffeta'),
('tricot'),
('rock-wool'),
('cellulose'),
('sateen'),
('nylon-mesh'),
('dri-lux'),
('100-percent-cotton-jersey'),
('mesh'),
('terry'),
('Cashmere'),
('rip-stop'),
('silk'),
('Blend'),
('tweed'),
('Jersey'),
('velour'),
('PolarGuard'),
('polyester'),
('nylon'),
('Chiffon'),
('Denim'),
('flat-knit'),
('plush'),
('metallic-fiber'),
('linen'),
('nonwoven-fabric'),
('suede'),
('double-weave'),
('wool'),
('Flannel'),
('quallofil'),
('neoprene'),
('thermax');

insert into amazon_sports.valid_battery_type values
('battery_type_d'),
('battery_type_a'),
('battery_type_c'),
('battery_type_lithium_ion'),
('battery_type_aaa'),
('battery_type_lithium_metal'),
('battery_type_9v'),
('battery_type_aa'),
('battery_type_12v'),
('battery_type_product_specific'),
('battery_type_p76'),
('battery_type_cr123a'),
('battery_type_aaaa'),
('battery_type_cr5'),
('battery_type_cr2');

insert into amazon_sports.valid_theme values
('Famous People'),
('Superhero'),
('Animal'),
('Occupational-Professional'),
('Humorous'),
('Fairytale'),
('Classic Monster'),
('Historical & Period'),
('Insects'),
('Western'),
('Science Fiction'),
('TV-Movies'),
('Food & Beverage'),
('Horror'),
('Sexy'),
('Scary'),
('Sports'),
('Religious'),
('Cartoon'),
('Mascots');

insert into amazon_sports.valid_condition_type values
('UsedGood'),
('CollectibleGood'),
('Club'),
('UsedLikeNew'),
('UsedVeryGood'),
('CollectibleAcceptable'),
('Refurbished'),
('New'),
('CollectibleLikeNew'),
('CollectibleVeryGood'),
('UsedAcceptable');

insert into amazon_sports.valid_resistance_mechanism values
('eddy-current-resistance-system'),
('ECB'),
('particle-brake-system'),
('manually-adjustable-magnetic-resistance'),
('pilates-flexbands'),
('electromagnetic'),
('pilates-fitness-circles'),
('exercise-straps'),
('resistance-bike-trainers');

insert into amazon_sports.valid_parent_child values
('parent'),
('child');

insert into amazon_sports.valid_gtin_exemption_reason values
('ReplacementPart'),
('CustomProductBundle');

insert into amazon_sports.valid_blade_length_unit_of_measure values
('FT'),
('CM'),
('MM'),
('M'),
('IN');

insert into amazon_sports.valid_country_as_labeled values
('Canada'),
('Guinea-Bissau'),
('Saint Helena'),
('Unknown'),
('Lithuania'),
('Cambodia'),
('Switzerland'),
('Ethiopia'),
('Aruba'),
('Swaziland'),
('Argentina'),
('Bolivia'),
('Cameroon'),
('Burkina Faso'),
('Turkmenistan'),
('Ghana'),
('Saudi Arabia'),
('Togo'),
('Japan'),
('Cape Verde'),
('Cocos (Keeling) Islands'),
('Slovenia'),
('Guatemala'),
('Bosnia and Herzegovina'),
('Kuwait'),
('Burma (Myanmar)'),
('Jordan'),
('Dominica'),
('Liberia'),
('Maldives'),
('Jamaica'),
('Oman'),
('Tanzania'),
('Martinique'),
('Saint Kitts And Nevis'),
('Ivory Coast'),
('Albania'),
('Gabon'),
('Niue'),
('Monaco'),
('Wallis and Futuna'),
('New Zealand'),
('Yemen'),
('Jersey'),
('Andorra'),
('Greenland'),
('Samoa'),
('Macau'),
('S. Georgia and S. Sandwich Isls.'),
('Norfolk Island'),
('United Arab Emirates'),
('Guam'),
('India'),
('Azerbaijan'),
('Lesotho'),
('Saint Vincent And The Grenadines'),
('Kenya'),
('South Korea'),
('Tajikistan'),
('Turkey'),
('Afghanistan'),
('Bangladesh'),
('Mauritania'),
('Solomon Islands'),
('Saint Lucia'),
('Hungary'),
('San Marino'),
('French Polynesia'),
('France'),
('Bermuda'),
('Slovakia'),
('Somalia'),
('Peru'),
('Laos'),
('Nauru'),
('Seychelles'),
('Norway'),
('Malawi'),
('Cook Islands'),
('Benin'),
('Western Sahara'),
('Cuba'),
('Republic of the Congo'),
('Mayotte'),
('China'),
('Armenia'),
('Dominican Republic'),
('Mongolia'),
('Ukraine'),
('Bahrain'),
('Tonga'),
('Finland'),
('Libya'),
('New Caledonia'),
('Cayman Islands'),
('Central African Republic'),
('Heard and McDonald Islands'),
('Mauritius'),
('Liechtenstein'),
('Australia'),
('Antigua And Barbuda'),
('Mali'),
('Russia'),
('Bulgaria'),
('United States'),
('Romania'),
('Angola'),
('French Southern Territories'),
('Chad'),
('South Africa'),
('Tokelau'),
('Cyprus'),
('Sweden'),
('Qatar'),
('Malaysia'),
('Austria'),
('Vietnam'),
('Mozambique'),
('Uganda'),
('Canary Islands'),
('British Virgin Islands'),
('Niger'),
('Isle of Man'),
('Brazil'),
('Turks And Caicos Islands'),
('Falkland Islands'),
('Faroe Islands'),
('Guinea'),
('Panama'),
('Costa Rica'),
('Luxembourg'),
('American Samoa'),
('Bahamas'),
('Gibraltar'),
('Ireland'),
('Pakistan'),
('Palau'),
('Nigeria'),
('Ecuador'),
('Czech Republic'),
('US Virgin Islands'),
('Brunei'),
('Belarus'),
('Iran'),
('Algeria'),
('Svalbard'),
('El Salvador'),
('Tuvalu'),
('Zaire'),
('Pitcairn Islands'),
('Saint Pierre and Miquelon'),
('Marshall Islands'),
('Chile'),
('Puerto Rico'),
('Belgium'),
('Kiribati'),
('Haiti'),
('Belize'),
('Hong Kong'),
('Sierra Leone'),
('Georgia'),
('Gambia'),
('Philippines'),
('Sao Tome And Principe'),
('Moldova'),
('Holy See (Vatican City)'),
('Croatia'),
('Micronesia'),
('Guernsey'),
('Thailand'),
('Namibia'),
('Grenada'),
('Iraq'),
('Portugal'),
('Estonia'),
('Uruguay'),
('Equatorial Guinea'),
('Lebanon'),
('Uzbekistan'),
('Tunisia'),
('Djibouti'),
('Rwanda'),
('Timor-Leste'),
('Spain'),
('Colombia'),
('Reunion'),
('Burundi'),
('Taiwan'),
('Fiji'),
('Barbados'),
('Madagascar'),
('Italy'),
('Bhutan'),
('Sudan'),
('Nepal'),
('Malta'),
('Democratic Republic of the Congo'),
('Netherlands'),
('Northern Mariana Islands'),
('Suriname'),
('Anguilla'),
('Venezuela'),
('Netherlands Antilles'),
('Aland Islands'),
('Israel'),
('Indonesia'),
('Iceland'),
('Zambia'),
('Senegal'),
('Papua New Guinea'),
('Zimbabwe'),
('Germany'),
('Vanuatu'),
('Denmark'),
('Saint-Martin'),
('Kazakhstan'),
('Poland'),
('Eritrea'),
('Kyrgyzstan'),
('Palestinian Territory'),
('British Indian Ocean Territory'),
('Montserrat'),
('Mexico'),
('Macedonia'),
('North Korea'),
('Sri Lanka'),
('Latvia'),
('Guyana'),
('Syria'),
('Guadeloupe'),
('Morocco'),
('Honduras'),
('Bouvet Island'),
('Egypt'),
('Nicaragua'),
('Singapore'),
('Serbia'),
('Botswana'),
('United Kingdom'),
('Trinidad And Tobago'),
('Antarctica'),
('Christmas Island'),
('Greece'),
('Paraguay'),
('French Guiana'),
('Comoros'),
('US Minor Outlying Islands');

insert into amazon_sports.valid_item_display_length_unit_of_measure values
('FT'),
('CM'),
('MM'),
('M'),
('IN');

insert into amazon_sports.valid_pad_type values
('self-inflating'),
('air-pump'),
('air'),
('ultralight'),
('foam');

insert into amazon_sports.valid_rise_style values
('Mid-Calf'),
('Knee High'),
('Socks'),
('Ankle'),
('No Show'),
('Thigh High');

insert into amazon_sports.valid_import_designation values
('Made in USA'),
('Made in USA or Imported'),
('Imported'),
('Made in USA and Imported');

